### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by DustyTech4** [plan-player-analytics/Plan#3007] opened 2023-05-06 17:33 UTC
### Describe the issue

getting an error message when loading the plugin

### Exceptions & Other Logs

```
87b9153c1b - Last occurred: 2023-05-06 Occurrences: 2
---- Context 2 ----
Plan v5.5 build 2307
Pufferfish+ (Purpur) git-PufferfishPlusPurpur-19 (MC: 1.19.4)
Server v1.19.4-R0.1-SNAPSHOT

Report and/or disable LibertyBans extension in the Plan config.
LibertyBans
Method:punishmentData

---- Context 1 ----
Plan v5.5 build 2307
Pufferfish+ (Purpur) git-PufferfishPlusPurpur-19 (MC: 1.19.4)
Server v1.19.4-R0.1-SNAPSHOT

Report and/or disable LibertyBans extension in the Plan config.
LibertyBans
Method:punishmentData

---- Stacktrace ----
com.djrapitops.plan.exceptions.DataExtensionMethodCallException: LibertyBans.punishmentData errored: java.lang.NullPointerException: address
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:56)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:322)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addDataFromAnotherBuilder(DataValueGatherer.java:310)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addValuesToBuilder2(DataValueGatherer.java:164)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addValuesToBuilder(DataValueGatherer.java:157)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.tryToUpdateValues(DataValueGatherer.java:342)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:331)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:181)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:165)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.gathering.events.PlayerJoinEventConsumer.lambda$updatePlayerDataExtensionValues$11(PlayerJoinEventConsumer.java:195)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
java.lang.reflect.InvocationTargetException
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:568)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:97)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:322)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addDataFromAnotherBuilder(DataValueGatherer.java:310)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addValuesToBuilder2(DataValueGatherer.java:164)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addValuesToBuilder(DataValueGatherer.java:157)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.tryToUpdateValues(DataValueGatherer.java:342)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:331)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:181)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:165)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.gathering.events.PlayerJoinEventConsumer.lambda$updatePlayerDataExtensionValues$11(PlayerJoinEventConsumer.java:195)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
java.lang.NullPointerException: address
   java.base/java.util.Objects.requireNonNull(Objects.java:235)
   LibertyBans-ClassLoader//space.arim.libertybans.core.selector.SelectionByApplicabilityImpl.<init>(SelectionByApplicabilityImpl.java:53)
   LibertyBans-ClassLoader//space.arim.libertybans.core.selector.SelectionByApplicabilityBuilderImpl.buildWith(SelectionByApplicabilityBuilderImpl.java:69)
   LibertyBans-ClassLoader//space.arim.libertybans.core.selector.SelectionByApplicabilityBuilderImpl.buildWith(SelectionByApplicabilityBuilderImpl.java:31)
   LibertyBans-ClassLoader//space.arim.libertybans.core.selector.SelectionBuilderBaseImpl.build(SelectionBuilderBaseImpl.java:108)
   LibertyBans-ClassLoader//space.arim.libertybans.core.selector.SelectionByApplicabilityBuilderImpl.build(SelectionByApplicabilityBuilderImpl.java:82)
   LibertyBans-ClassLoader//space.arim.libertybans.core.selector.SelectionByApplicabilityBuilderImpl.build(SelectionByApplicabilityBuilderImpl.java:31)
   LibertyBans_Release-1.1.0-M2.jar//space.arim.libertybans.api.select.PunishmentSelector.getApplicablePunishment(PunishmentSelector.java:135)
   Plan-5.5-build-2307.jar//net.playeranalytics.extension.libertybans.LibertyBansExtension.punishment(LibertyBansExtension.java:80)
   Plan-5.5-build-2307.jar//net.playeranalytics.extension.libertybans.LibertyBansExtension.punishmentData(LibertyBansExtension.java:98)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:568)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:97)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:322)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addDataFromAnotherBuilder(DataValueGatherer.java:310)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addValuesToBuilder2(DataValueGatherer.java:164)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addValuesToBuilder(DataValueGatherer.java:157)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.tryToUpdateValues(DataValueGatherer.java:342)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:331)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:181)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:165)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.gathering.events.PlayerJoinEventConsumer.lambda$updatePlayerDataExtensionValues$11(PlayerJoinEventConsumer.java:195)
   Plan-5.5-build-2307.jar//com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
```

### Plugin versions

plan-5.5-build2307

**Comment by AuroraLS3** [comment] 2023-05-07 03:50
This has been fixed but not yet released - you can download a dev release here https://github.com/plan-player-analytics/Plan/actions/workflows/ci.yml?query=branch%3Amaster

Duplicate of https://github.com/plan-player-analytics/Plan/issues/2948

**Closed by AuroraLS3** 2023-05-07 03:50 UTC
Labels: Bug
