### ISSUE TITLE
plan_kills Not recording End Crystal PvP Death

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#1799] opened 2021-03-16 20:49 UTC
### Describe the issue
Trying to query for all End Crystal deaths as this seems to be a new trend to quickly kill someone in PvP now by putting obsidian floor around your base, but it does not seem to be tracked in Plan. I guess it's because it needs to be placed and then broken to explode. Its quite a common way to kill someone, its rare that someone uses End Crystals for their intended purpose! Is there any way this can track PvP kills, it's usually someone that will hit/snipe an end crystal to blow someone else up.

### Additional information
I am running Paper 1.12.2 if this makes any difference.

**Comment by AuroraLS3** [comment] 2021-03-17 06:10
Duplicate of #1571 - I'll bump that up in priority

**Closed by AuroraLS3** 2021-03-17 06:10 UTC
Labels: Bug

**Comment by TomLewis** [comment] 2021-03-17 09:51
Somehow End Crystal bombing became very popular! Thanks!

**Comment by AuroraLS3** [comment] 2021-03-17 09:54
It's probably a lot more effective than tnt for sure!
