### ISSUE TITLE
2 Sessions for 1 login and logout

### ISSUE THREAD

**Issue by ChrisWard316** [plan-player-analytics/Plan#1403] opened 2020-04-19 12:05 UTC
### Describe the issue
I'm trying to convert from onTime so i was looking deep into the structure of how the plugin works via MYSQL and i logged into my "hub" and logged out and it has created 2 rows with the exact same data instead of just 1 row.

See here: http://ximg.co.uk/images/2020/04/19/db.png

**Comment by Rsl1122** [comment] 2020-04-19 12:07
![kuva](https://user-images.githubusercontent.com/24460436/79687362-6d89dc00-824f-11ea-92aa-d530572e0627.png)

**Comment by ChrisWard316** [comment] 2020-04-19 15:57
Fixed

**Comment by Rsl1122** [comment] 2020-04-19 16:44
I could not reproduce this issue with bungeecord and paper, could you provide some steps on how to reproduce the issue

**Comment by ChrisWard316** [comment] 2020-04-21 09:53
I've just reinstalled the whole setup and it's made 2 records again of the same data in sessions.

- Turn off BungeeCord
- put plan in plugins folder
- Turn on BungeeCord
- Turn off Bungee Cord / Add MYSQL data 
- change Network ip from 0.0.0.0 (as you get an error) to 127.0.0.1 
- Change Network name from Plan To MCBuffalo
- Turn on BungeeCord

- Turn off Hub, Install plugin, Turn on HUB, Turn off again
- Add MYSQL DATA
- Change Network name from Plan To Hub
- change Disable_Webserver to false
- Turn on HUB

Logout and in on the server and i have 2 of the exact same sessions just different ID'S

@Rsl1122

**Comment by ChrisWard316** [comment] 2020-04-24 11:11
I don't know if this will help you but i went all the way back to 5.0 build 249 to try find a working version that i can use in the meantime.

The same issue still exists but the 2 records it creates are of different values
http://ximg.co.uk/images/2020/04/24/2.png

**Comment by Rsl1122** [comment] 2020-04-24 13:00
I was not able to reproduce the issue on a fresh install with the steps provided.

This issue is definitely due to something in your specific setup, because 5.0 build 249 has been out for months. It would have been reported in great numbers.

Could you send list of plugins on your Bungeecord and Hub server to see if any of the plugins cause `PlayerQuitEvent` to trigger twice on leave

**Comment by AuroraLS3** [comment] 2021-03-19 15:00
Might be fixed in 5.2 build 1115 - There was some code that was referring to variables in odd ways which could have lead to the active session being stored a 2nd time upon logout. I'm not sure if this is how it happened, but it should now be impossible since the type system doesn't allow unfinished sessions to be stored.

**Closed by AuroraLS3** 2021-03-19 15:00 UTC
Labels: Bug, note: Could not reproduce
