### ISSUE TITLE
IncompatibleClassChangeError in PLAN on update to DiscordSRV 1.27.0 

### ISSUE THREAD

**Issue by mercurialmusic** [plan-player-analytics/Plan#3400] opened 2024-01-07 00:16 UTC
### Describe the issue

Hello! Getting a IncompatibleClassChangeError  with the new DiscordSRV 1.27.0 builds with Plan-5.6-build-2614

### Exceptions & Other Logs
Console Error:
https://gist.github.com/mercurialmusic/7359fd33ab9c609ed9e0aff28725e606

PLAN Log:
https://gist.github.com/mercurialmusic/4a024ae0379a93c32af578c9a8733863

### Plugin versions

Plan-5.6-build-2614
DiscordSRV-Build-1.27.0
git-Paper-378 (MC: 1.20.4)

Thanks!

**Comment by AuroraLS3** [comment] 2024-01-07 06:27
Duplicate of #3399 you'll find fix there

**Closed by AuroraLS3** 2024-01-07 06:27 UTC
Labels: Bug

**Comment by mercurialmusic** [comment] 2024-01-07 21:16
Oop, sorry about that, and thanks!
