### ISSUE TITLE
BadRequestException | Failed to generate Analysis Page

### ISSUE THREAD

**Issue by falceso** [plan-player-analytics/Plan#945] opened 2019-03-05 07:26 UTC
### Describe the bug

Unable to access the /server/{server} page.

### Server information

**Plan Version:** 4.7.0
**Server:** BungeeCord git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259 (git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259)
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.15.0-45-generic
**Java Version:** 1.8.0_181, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.181-b13, Oracle Corporation

### Exceptions & Other Logs

```[02:07:20 WARN] [Plan]: Error was caught by com.djrapitops.plan.system.webserver.response.ResponseFactory
com.djrapitops.plan.api.exceptions.connection.BadRequestException: Bad Request: https://[redacted]/info/generateanalysispagerequest | sender=533ae4b7-b3e2-35b2-a196-97c07b098548;&variable;type=GenerateAnalysisPageRequest;&variable;server=c6d8a7ff-35f0-3b12-975f-e8298afe85a3
at com.djrapitops.plan.system.info.connection.ConnectionOut.handleResult(ConnectionOut.java:133) ~[?:?]
at com.djrapitops.plan.system.info.connection.ConnectionOut.sendRequest(ConnectionOut.java:110) ~[?:?]
at com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:87) ~[?:?]
at com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:79) ~[?:?]
at com.djrapitops.plan.system.info.InfoSystem.sendRequest(InfoSystem.java:118) ~[?:?]
at com.djrapitops.plan.system.info.InfoSystem.generateAnalysisPage(InfoSystem.java:99) ~[?:?]
at com.djrapitops.plan.system.webserver.pages.ServerPageHandler.lambda$refreshNow$3(ServerPageHandler.java:108) ~[?:?]
at com.djrapitops.plan.system.processing.Processing.lambda$submitNonCritical$0(Processing.java:73) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

[02:07:37 WARN] [Plan]: Error was caught by com.djrapitops.plan.system.webserver.response.ResponseFactory
com.djrapitops.plan.api.exceptions.connection.BadRequestException: Bad Request: https://[redacted]/info/generateanalysispagerequest | sender=533ae4b7-b3e2-35b2-a196-97c07b098548;&variable;type=GenerateAnalysisPageRequest;&variable;server=4acd4b54-5a46-3800-b140-2a27c269e3ad
at com.djrapitops.plan.system.info.connection.ConnectionOut.handleResult(ConnectionOut.java:133) ~[?:?]
at com.djrapitops.plan.system.info.connection.ConnectionOut.sendRequest(ConnectionOut.java:110) ~[?:?]
at com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:87) ~[?:?]
at com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:79) ~[?:?]
at com.djrapitops.plan.system.info.InfoSystem.sendRequest(InfoSystem.java:118) ~[?:?]
at com.djrapitops.plan.system.info.InfoSystem.generateAnalysisPage(InfoSystem.java:99) ~[?:?]
at com.djrapitops.plan.system.webserver.pages.ServerPageHandler.lambda$refreshNow$3(ServerPageHandler.java:108) ~[?:?]
at com.djrapitops.plan.system.processing.Processing.lambda$submitNonCritical$0(Processing.java:73) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

### Additional information

I've updated from the 4.7.0DEV3 and restarted all servers. Currently using the jar from GitHub release. GitHub suggested #935 

```
[02:17:58 INFO]: CONSOLE executed command: /planbungee con
=> [02:17:58 INFO]: https://[redacted]: HTTPS : External : To:Fail : From:Fail
> [02:17:58 INFO]: Fail reason: Older Plan version on receiving server
> [02:17:58 INFO]: https://[redacted]: HTTPS : External : To:Fail : From:Fail
> [02:17:58 INFO]: Fail reason: Older Plan version on receiving server
> [02:17:58 INFO]: https://[redacted]: HTTPS : External : To:Fail : From:Fail
> [02:17:58 INFO]: Fail reason: Older Plan version on receiving server
> [02:17:58 INFO]: https://[redacted]: HTTPS : External : To:Fail : From:Fail
> [02:17:58 INFO]: Fail reason: Older Plan version on receiving server
> [02:17:58 INFO]: https://[redacted]: HTTPS : External : To:Fail : From:Fail
> [02:17:58 INFO]: Fail reason: Older Plan version on receiving server
```
**Frequency of occurrence**: When opening some or all server pages.

**Other:**
Unknown.

**Comment by Rsl1122** [comment] 2019-03-05 07:40
Could you try running `/plan analyze` on one of the servers to see if it fails to send the result to Bungee.

(Check the server's console for errors & check the /server/name page)

**Comment by Rsl1122** [comment] 2019-03-05 12:11
Alright lets see..

BadRequestException (400) on /info/generateanalysispagerequest, This can occur if
- 'sender' variable is not supplied in the request. This is not the case since it was supplied
- 'server' variable is not supplied in the request. This is not the case since it was supplied
- The sent 'server' variable does not match the server's UUID it was sent to
- If any follow-up requests return a 400
  - CacheAnalysisPageRequest did not have 'sender' or 'html' variable (Unlikely)

"Older Plan version on receiving server" message is displayed when the receiving server returns a 404. This can occur if
- The server was not a Plan webserver
- The server had no server to send the request to (This should resolve itself every 15 seconds, so it is unlikely)
- The info request was not registered on the receiving server
  - This can occur if the partially enables. It's unlikely that all servers failed to start in the same way

----

It is very peculiar bug since this area was not touched between DEV3 and release.

Additional information might help figuring out the issue:
- On `/debug` page Under "Server Information" there is `### Connection log`, please get this information from both bungee (`bungee_address:port/debug`) and a server (`server_address:port/debug`)
- A connection debug attempt on a server (`/plan m con`)
- Results of `/plan analyze` on console of a server
- Any errors

**Comment by falceso** [comment] 2019-03-05 16:07
### Connection Log on bungeecord:

Server Address | Request Type | Response | Sent
-- | -- | -- | --
172.18.0.1 | In:  /info/cacheanalysispagerequest | 200 | Today, 10:06:43

### Connection Log on Lobby:

Server Address | Request Type | Response | Sent
-- | -- | -- | --
https://[redacted]:xxx4 | Out: CacheAnalysisPageRequest | 200 | Today, 10:02:20

### Connection Log on Creative:

Server Address | Request Type | Response | Sent
-- | -- | -- | --
https://[redacted]:xxx4 | Out: CacheAnalysisPageRequest | 200 | Today, 10:06:43

---
### Connection Debug attempt from Creative server
plan m con=> [11:01:20 INFO]: https://mqc3py76k5d4yjcn.minestar.network: HTTPS : External : To:OK : From:OK
[11:01:21 INFO]: https://[redacted]: HTTPS : External : To:OK : From:OK
[11:01:21 INFO]: https://[redacted]: HTTPS : External : To:OK : From:OK
[11:01:21 INFO]: https://[redacted]:xxx4: HTTPS : External : To:OK : From:OK
[11:01:21 INFO]: https://[redacted]: HTTPS : External : To:OK : From:OK

..Provides a working link to the Creative server thru the network page..

Everything is working again and the analytics page is being cached now... So yeah.. I'm confused, but alright then.

**Comment by Rsl1122** [comment] 2019-03-05 16:24
My best guess is that some database patches were being applied and some part malfunctioned because of it (likely the server connection system was unable to fetch the server information)

Closing since it appears functioning now.

**Comment by Rsl1122** [comment] 2019-03-07 09:49
Since this bug resurfaced, I might need more information about the locations of the servers, eg "same machine", "on local network", "on different network" as well as information if any are using `localhost` `<empty>` or `127.0.0.1` as the address

**Comment by falceso** [comment] 2019-03-07 15:21
* Same machine
* Using pterodactyl
* Was working before
* Using public IP and is publicly accessible.
* Nginx reverse proxy
* Only 1 server is down. (On purpose)
* All data moved back to Not being cached.

Seems the issue hasn't cleared it self with time.

**Comment by Rsl1122** [comment] 2019-03-07 17:10
This is a very peculiar bug.

You can downgrade the Bungee server to 4.6.2 to see if that solves the issue temporarily until I figure this thing out.

**Comment by falceso** [comment] 2019-03-08 05:50
Just adding some more gas to the :fire:. It appears to have the same issue on 4.6.2 what a very specific / selective bug.

**Comment by Rsl1122** [comment] 2019-03-08 07:15
If you downgraded just the bungee and not the others then that says that the issue is on the Bukkit side on 4.7.0+

Did you downgrade just the bungee server?

**Comment by falceso** [comment] 2019-03-08 15:08
Ah, well I downgraded all the servers.

**Comment by Rsl1122** [comment] 2019-03-08 15:13
And the error didn't go away after that? That's very odd

**Comment by falceso** [comment] 2019-03-13 07:39
```
[00:17:42 INFO] [Plan]: [DEBUG] [] ConnectionIn: GenerateAnalysisPageRequest
[00:17:42 INFO] [Plan]: [DEBUG] [Connections] ConnectionIn: /info/generateanalysispagerequest from xxx
[00:17:42 INFO] [Plan]: [DEBUG] [Connections] ConnectionOut: GenerateAnalysisPageRequest to https://xxx
[00:17:42 INFO] [Plan]: [DEBUG] [InfoRequests] Exception during request: com.djrapitops.plan.api.exceptions.connection.BadRequestException: Bad Request: https://xxx/info/generateanalysispagerequest | sender=533ae4b7-b3e2-35b2-a196-97c07b098548;&variable;type=GenerateAnalysisPageRequest;&variable;server=d1a72fd3-3658-3369-b8b5-0ac577a2b243, running locally.
[00:17:42 WARN] [Plan]: Error was caught by com.djrapitops.plan.system.webserver.response.ResponseFactory
com.djrapitops.plan.api.exceptions.connection.BadRequestException: Bad Request: https://xxx/info/generateanalysispagerequest | sender=533ae4b7-b3e2-35b2-a196-97c07b098548;&variable;type=GenerateAnalysisPageRequest;&variable;server=d1a72fd3-3658-3369-b8b5-0ac577a2b243
at com.djrapitops.plan.system.info.connection.ConnectionOut.handleResult(ConnectionOut.java:133) ~[?:?]
at com.djrapitops.plan.system.info.connection.ConnectionOut.sendRequest(ConnectionOut.java:110) ~[?:?]
at com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:87) ~[?:?]
at com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:79) ~[?:?]
at com.djrapitops.plan.system.info.InfoSystem.sendRequest(InfoSystem.java:118) ~[?:?]
at com.djrapitops.plan.system.info.InfoSystem.generateAnalysisPage(InfoSystem.java:99) ~[?:?]
at com.djrapitops.plan.system.webserver.pages.ServerPageHandler.lambda$refreshNow$3(ServerPageHandler.java:108) ~[?:?]
at com.djrapitops.plan.system.processing.Processing.lambda$submitNonCritical$0(Processing.java:73) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
One Server I was messing around with..
```[00:41:53] [Plan Non critical-pool-0/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:41:53] [Plan Non critical-pool-0/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:41:59] [Plan Non critical-pool-3/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:41:59] [Plan Non critical-pool-3/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:05] [Plan Non critical-pool-5/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:05] [Plan Non critical-pool-5/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:05] [Plan Non critical-pool-4/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:05] [Plan Non critical-pool-4/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:10] [Server thread/INFO]: [Plan] [DEBUG] [] First run of TPSCountTimer Task.
[00:42:11] [Plan Non critical-pool-2/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:11] [Plan Non critical-pool-2/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:12] [Plan Non critical-pool-0/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:12] [Plan Non critical-pool-0/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:18] [Plan Non critical-pool-3/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:18] [Plan Non critical-pool-3/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:22] [Craft Scheduler Thread - 13/INFO]: [Plan] [DEBUG] [] Config Store Task - Config in db now up to date.
[00:42:24] [Plan Non critical-pool-5/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:24] [Plan Non critical-pool-5/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:24] [Plan Non critical-pool-4/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:24] [Plan Non critical-pool-4/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:30] [Plan Non critical-pool-2/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:30] [Plan Non critical-pool-2/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:31] [Plan Non critical-pool-0/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:31] [Plan Non critical-pool-0/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:37] [Plan Non critical-pool-3/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:37] [Plan Non critical-pool-3/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:43] [Plan Non critical-pool-5/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://[redacted]:xx04: Network is unreachable (connect failed)
[00:42:43] [Plan Non critical-pool-5/INFO]: [plan.org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://[redacted]:xx04
[00:42:43] [Plan Non critical-pool-4/INFO]: [Plan] [DEBUG] [Connections] ConnectionOut: CacheAnalysisPageRequest to https://[redacted]:xx04
[00:42:43] [Plan Non critical-pool-4/INFO]: [Plan] [DEBUG] [InfoRequests] Exception during request: com.djrapitops.plan.api.exceptions.connection.ConnectionFailException: Connection failed to address: https://[redacted]:xx04 - Make sure the server is online., running locally.
[00:42:43] [Plan Non critical-pool-4/INFO]: [Plan] [DEBUG] [InfoRequests] Local: CacheAnalysisPageRequest
```

BungeeCord Log:
```
[01:15:20] [Plan WebServer Thread-0/INFO] [Plan]: [DEBUG] [] ConnectionIn: GenerateAnalysisPageRequest
[01:15:20] [Plan WebServer Thread-0/INFO] [Plan]: [DEBUG] [Connections] ConnectionIn: /info/generateanalysispagerequest from [IP]
[01:15:20] [Plan Non critical-pool-1/INFO] [Plan]: [DEBUG] [Connections] ConnectionOut: GenerateAnalysisPageRequest to https://[redacted]
[01:15:20] [Plan Non critical-pool-1/INFO] [Plan]: [DEBUG] [InfoRequests] Exception during request: com.djrapitops.plan.api.exceptions.connection.BadRequestException: Bad Request: https://[redacted]/info/generateanalysispagerequest | sender=533ae4b7-b3e2-35b2-a196-97c07b098548;&variable;type=GenerateAnalysisPageRequest;&variable;server=4acd4b54-5a46-3800-b140-2a27c269e3ad, running locally.
[01:15:20] [Plan Non critical-pool-1/WARN] [Plan]: Error was caught by com.djrapitops.plan.system.webserver.response.ResponseFactory
com.djrapitops.plan.api.exceptions.connection.BadRequestException: Bad Request: https://[redacted]/info/generateanalysispagerequest | sender=533ae4b7-b3e2-35b2-a196-97c07b098548;&variable;type=GenerateAnalysisPageRequest;&variable;server=4acd4b54-5a46-3800-b140-2a27c269e3ad
	at com.djrapitops.plan.system.info.connection.ConnectionOut.handleResult(ConnectionOut.java:133) ~[?:?]
	at com.djrapitops.plan.system.info.connection.ConnectionOut.sendRequest(ConnectionOut.java:110) ~[?:?]
	at com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:87) ~[?:?]
	at com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:79) ~[?:?]
	at com.djrapitops.plan.system.info.InfoSystem.sendRequest(InfoSystem.java:118) ~[?:?]
	at com.djrapitops.plan.system.info.InfoSystem.generateAnalysisPage(InfoSystem.java:99) ~[?:?]
	at com.djrapitops.plan.system.webserver.pages.ServerPageHandler.lambda$refreshNow$3(ServerPageHandler.java:108) ~[?:?]
	at com.djrapitops.plan.system.processing.Processing.lambda$submitNonCritical$0(Processing.java:73) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[01:15:43] [Plan Pool Thread #7/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@11acdc30, id=66, owner=com.djrapitops.plan.PlanBungee@350ec690, task=com.djrapitops.plugin.task.bungee.BungeeRunnableFactory$1@d3f4505, delay=62000, period=0, running=true) encountered an exception
java.lang.NullPointerException: null
	at com.djrapitops.plan.system.tasks.proxy.NetworkConfigStoreTask.updateDBConfigs(NetworkConfigStoreTask.java:53) ~[?:?]
	at com.djrapitops.plan.system.tasks.proxy.NetworkConfigStoreTask.run(NetworkConfigStoreTask.java:46) ~[?:?]
	at com.djrapitops.plugin.task.bungee.BungeeRunnableFactory$1.run(BungeeRunnableFactory.java:55) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]```

**Note: Out of frustration. I just wiped Plan for a reinstall.**

**Closed** 2019-04-02 16:15 UTC
Labels: Bug, status: Solved on Discord
