### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by mibby** [plan-player-analytics/Plan#2101] opened 2021-09-27 09:02 UTC
### Describe the issue

java.lang.UnsupportedOperationException

### Exceptions & other logs

```text
a86250f8a3 - Last occurred: 2021-09-27 Occurrences: 1
---- Context 1 ----
Plan v5.4 build 1445
Purpur git-Purpur-1394 (MC: 1.17.1)
Server v1.17.1-R0.1-SNAPSHOT

Report this
Placeholder Request
server_uuid
24b95709-012c-4dee-a324-c37ff1a4e56c

---- Stacktrace ----
java.lang.UnsupportedOperationException
   java.base/java.util.AbstractList.remove(AbstractList.java:167)
   Plan-5.4-dev-build-1445.jar//com.djrapitops.plan.addons.placeholderapi.PlanPlaceholderExtension.parseParameters(PlanPlaceholderExtension.java:124)
   Plan-5.4-dev-build-1445.jar//com.djrapitops.plan.addons.placeholderapi.PlanPlaceholderExtension.getPlaceholderValue(PlanPlaceholderExtension.java:102)
   Plan-5.4-dev-build-1445.jar//com.djrapitops.plan.addons.placeholderapi.PlanPlaceholderExtension.lambda$getCached$0(PlanPlaceholderExtension.java:135)
   Plan-5.4-dev-build-1445.jar//com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   java.base/java.lang.Thread.run(Thread.java:831)
```

### Plugin versions

PlaceholderAPI-2.10.10-DEV-132

**Comment by AuroraLS3** [comment] 2021-09-27 10:13
Duplicate of https://github.com/plan-player-analytics/Plan/issues/2096 - that ticket has another dev build with this fixed

**Closed by AuroraLS3** 2021-09-27 10:13 UTC
Labels: Bug
