### ISSUE TITLE
Add CraftingStore support

### ISSUE THREAD

**Issue by Fer-Jgu** [plan-player-analytics/Plan#2199] opened 2021-12-11 07:03 UTC
### I would like to be able to..

Use CraftingStore stuff just as Buycraft is showcased in the [Supported plugins](https://github.com/plan-player-analytics/Plan/wiki/Supported-Plugins) section.

### Is your feature request related to a problem? Please describe.

Nope, just would be cool :)

**Comment by AuroraLS3** [comment] 2021-12-11 07:27
Duplicate of #1917 - Follow that ticket instead

**Closed by AuroraLS3** 2021-12-11 07:27 UTC
