### ISSUE TITLE
Plugin boxes overlapping on the website

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [plan-player-analytics/Plan#2180] opened 2021-12-01 22:08 UTC
### Describe the issue

It seems like that when you have a ban history, with 1 ban already it does overlap into the below part of another plugin. A second ban doesn't even seem to be displayed in this case. 

I tested it by banning my alt twice.

It looks like this after both, a single and a second ban:
Lobby overview:
https://prnt.sc/21awr7g
Citybuild overview:
https://prnt.sc/21awtoe

I included multiple sub servers to show that it also happens with multiple pages.

### Exceptions & other logs

```text
To not lap into other stats and multiple stats are being displayed, eventually with a arrow click or slider
```

### Plugin versions

Latest Litebans, Latest Plan

### Additional information

-

**Comment by AuroraLS3** [comment] 2021-12-02 13:33
There seems to be some content placement issue with bootstrap.

Were you using a phone to view this?

**Comment by ILikeOrangeJuice** [comment] 2021-12-03 15:58
Sorry for the late reply, got my 3rd shot and were bleh haha.
I used my pc, however it happens with both iirc.

**Comment by AuroraLS3** [comment] 2021-12-15 10:52
This seems to be an issue with bootstrap masonry panes

**Comment by AuroraLS3** [comment] 2022-02-06 16:51
Reproduced the issue. The issue can happen when tab on the card is changed, so the content of the card changes but masonry is not notified of the change in DOM.

**Comment by AuroraLS3** [comment] 2023-01-25 15:03
This should be fixed on the Frontend BETA version of frontend (Enable from config `Plugin.Frontend_BETA`)

I'll reopen if it happens again

**Closed by AuroraLS3** 2023-01-25 15:03 UTC
Labels: Bug, status: Reproduced, JavaScript & HTML, Under Review 🕵️, DataExtensions
