### ISSUE TITLE
Error when disconnecting a player

### ISSUE THREAD

**Issue by AlexRahvalov** [plan-player-analytics/Plan#3113] opened 2023-07-10 06:41 UTC
### Describe the issue
When disconnecting a player from the server, an error occurs...

"[09:30:56 ERROR]: [Plan] Ran into ClassCastException - logged to plugins/Plan/logs/ClassCastException-cc764f7f02.txt
[09:30:56 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[09:30:56 ERROR]: [Plan] Error msg: "class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @7ab2bfe1)""

### Exceptions & Other Logs

latest log: https://mclo.gs/ejMOvNF
log from /plugins/Plan/logs: https://mclo.gs/dwqyxyg

### Plugin versions

Plan-5.5-dev-build-2411

### Additional information

purpur-1.20.1-2011

**Comment by AuroraLS3** [comment] 2023-07-10 07:37
Duplicate of #3098 - downgrade to paper 62

**Closed by AuroraLS3** 2023-07-10 07:37 UTC
Labels: Bug
