### ISSUE TITLE
Network: Clicking players from a server playerlist does not send to the correct URL, 404.

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#2358] opened 2022-05-06 11:10 UTC
### Describe the issue
I have a self-hosted, Bungee network setup.
if I visit My survival analyics, click players, click on a player, it 404's.
I think this is just a bad URL, because if I remove /server/ from the URL, it shows me the player page.

https://panel.fakedomain.com/server/player/4930de2b-5b3b-4660-8c55-e2a0db07d91d

But this works

https://panel.fakedomain.com/player/4930de2b-5b3b-4660-8c55-e2a0db07d91d

**Comment by AuroraLS3** [comment] 2022-05-06 13:36
Ah I see, this is probably what that other ticket was talking about (I closed it as "could not reproduce") but I didn't realize they were using export!

**Comment by AuroraLS3** [comment] 2022-05-26 06:23
Hmm, I wonder - does the address have a slash at the end when you access the exported server page? (eg. `/server/Lobby/` instead of `/server/Lobby`

**Comment by TomLewis** [comment] 2022-05-26 08:22
> Hmm, I wonder - does the address have a slash at the end when you access the exported server page? (eg. `/server/Lobby/` instead of `/server/Lobby`) - Plan assumes it doesn't

Yes it does! I wonder if this is an Nginx thing?

**Comment by AuroraLS3** [comment] 2022-05-26 11:03
I am unsure, it could also be because the exported file is `/server/Lobby/index.html` - At least now I know what to do to fix it, some js magic needs to detect if there's a slash at the end :)

**Closed** 2023-01-22 12:56 UTC
Labels: Bug, Export, Frontend BETA
