### ISSUE TITLE
High Timings

### ISSUE THREAD

**Issue by JammMusic** [plan-player-analytics/Plan#1289] opened 2020-01-12 17:30 UTC
This plugin shows up at the top of my timings for all plugins. Is there any way to lower the impact it has on the server? There were 65 players on during this sample.

https://i.imgur.com/Ev1AJGy.png

Server Software: Paper 1.14.4

**Comment by Rsl1122** [comment] 2020-01-13 09:24
Looks like it is the TPSCounter that runs every second, also gathering other data such as CPU, RAM, Chunks & Entities. (I recon the 12ms mostly consists of the entities&chunks count)

The situation doesn't look dire yet (12ms on one tick, 0ms on 19 ticks = ~1.2% of 20 ticks), but I can add settings for chunk & entity gathering and then optimize the counter to do a bit less work.

----

I'll post a dev build here when a remedy is available.

**Comment by Rsl1122** [comment] 2020-01-14 20:11
Here is a dev build with an optimized version of the task.
https://github.com/plan-player-analytics/Plan/releases/tag/5.0.361

I used Paper timings to optimize, and the above build did not show the task in Lag-timings (anymore).

----

Here are the causes for the 12ms average that were identified and dealt with during the optimization:
- Getting CPU load takes 500-900ms on the first call after the JVM has started. - *Fixed by calling the method async before the task runs for the first time.*
- Counting Entities used Stream API (which might be slower on first few runs) - *Replaced with for loops*
- Counting Entities and Chunks were looping through worlds twice - *Combined the for loops*
- Array Copy for 60 entries when saving the average for one minute - *Removed use of List and replaced with cheap math operations
- Minor GC operation when saving the TPS - *Impact minimal (Doesn't show up in Timings), was not considered an issue*

New task averaged under 1 ms (~190000ns with my benchmarks)

**Closed** 2020-01-17 19:26 UTC
Labels: Improvement
