### ISSUE TITLE
Litebans header in wrong order / missing a couple entries

### ISSUE THREAD

**Issue by untuned** [plan-player-analytics/Plan#1365] opened 2020-03-20 02:42 UTC
### Describe the issue

The reason is supposed to be UUID / username, etc.
Should be in this order: Username, Reason, Given date, Given by, Expiry (N/A if permanent)

### Server information

**Plan Version:** 5.0 build 415
**Server:** Tuinity 1.15.2-R0.1-SNAPSHOT (git-Tuinity-"d16b788" (MC: 1.15.2))
**Database:** SQLite

**Operating SubSystem:** Windows 10 (amd64) version 10.0
**Java Version:** 11.0.6, Oracle Corporation
**Java VM Version:** Java HotSpot(TM) 64-Bit Server VM version 11.0.6+8-LTS, Oracle Corporation
### Benchmarks
```
312 ms     -48 MB  Enable
12 ms      -1 MB   subsystem-enable
```

### Exceptions & Other Logs

![](https://untnd.me/wqwbzeZoe)

**Comment by Rsl1122** [comment] 2020-03-20 07:44
Duplicate of #1355

Follow that issue for resolution.

**Closed by Rsl1122** 2020-03-20 07:44 UTC
Labels: Bug
