### ISSUE TITLE
PostgresSQL

### ISSUE THREAD

**Issue by SemperEtAnte** [plan-player-analytics/Plan#1547] opened 2020-08-08 08:25 UTC
Hello. There was such a question, perhaps even a topic for discussion: I began to transfer plugins on my server to PostgreSQL and here it turned out that this plugin does not support working with it, is there a fork or is it possible to add support for this database?

**Comment by Rsl1122** [comment] 2020-08-08 08:35
Duplicate of #1197 

See that ticket for reasoning why this feature was considered 'Out of scope'

**Closed by Rsl1122** 2020-08-08 08:35 UTC
