### ISSUE TITLE
Legacy org.bukkit.event.player.AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by JanReich** [plan-player-analytics/Plan#3782] opened 2024-09-13 18:54 UTC
### Describe the issue
Plugin uses deprecated ChatEvent event -> AsyncPlayerChatEvent 
https://jd.papermc.io/paper/1.21.1/org/bukkit/event/player/AsyncPlayerChatEvent.html

### Exceptions & Other Logs
[17:26:42 INFO]: [SignedVelocity] Enabling SignedVelocity v1.2.3
[17:26:42 WARN]: [SignedVelocity] ------------------------------
[17:26:42 WARN]: [SignedVelocity] The following plugins have listener in legacy org.bukkit.event.player.AsyncPlayerChatEvent event: SuperiorSkyblock2, Plan.
[17:26:42 WARN]: [SignedVelocity] This may negatively affect the functionality of SignedVelocity,
[17:26:42 WARN]: [SignedVelocity] please report to the author to use Paper's AsyncChatEvent and/or AsyncChatDecorateEvent.
[17:26:42 WARN]: [SignedVelocity] ------------------------------

### Additional information
SuperiorSkyBlock had a simular issue and they had already fix this
https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/2227

**Comment by Vankka** [comment] 2024-09-14 13:21
Duplicate of https://github.com/plan-player-analytics/Plan/issues/3423

**Closed** 2024-09-14 13:32 UTC
Labels: Bug, Duplicate
