### ISSUE TITLE
Exported player's pages hold no values

### ISSUE THREAD

**Issue by TripleNothing** [plan-player-analytics/Plan#1223] opened 2019-11-12 14:22 UTC
### Describe the issue
['players'](https://minecraft.hellzoneinc.com/player-analytics/players/) loads its listing just fine and appears to provide all the intended values.
['player'](https://minecraft.hellzoneinc.com/player-analytics/player/Triple_Nothing/) provides the page's structure, but displays no values but the player's name.
Issue applies to all pages within 'player' EXCEPT Plugins. Those seem to display as intended. Just to rule out any prior/carry-over, all of Plan was removed & re-placed fresh to test a fresh install.

Exported files for external webserver.

### Server information
Ubuntu 18.04 LTS
BungeeCord Build 1421 (Most recent at this moment)
PaperSpigot 1.14.4 Build 226 (Most recent at this moment)
Player Analytics 5.0 Build 279 (Most recent at this moment)

### Exceptions & Other Logs
Initial logs and such crystal clear. I JUST enabled Debug & Dev and will add any additions, if exist.

**Comment by Rsl1122** [comment] 2019-11-12 14:51
Oops I forgot to fix this because there wasn't an issue open. Thanks for opening an issue about this.

**Comment by Rsl1122** [comment] 2019-11-12 17:43
Fixed in build 283
https://plan.djrapitops.com/job/Player%20Analytics/job/master/

**Comment by TripleNothing** [comment] 2019-11-13 01:40
Nothing appears fixed, and even enabling Debug & Dev for logs, nothing looks to error.
[Debug/Dev Log](http://projects.hellzoneinc.com/DebugLog-2019_11_12.txt)
The [player](https://minecraft.hellzoneinc.com/player-analytics/player/Triple_Nothing/) still is missing items.

**Closed** 2019-11-14 17:03 UTC
Labels: Bug, Export

**Comment by Rsl1122** [comment] 2019-11-14 17:07
Confirmed fixed in build 284 https://plan.djrapitops.com/job/Player%20Analytics/job/master/
The cause of the issue (pretty dumb) can be found in the commit message.
