### ISSUE TITLE
RuntimeException: Failed to load driver class plan.com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader

### ISSUE THREAD

**Issue by mibby** [plan-player-analytics/Plan#1922] opened 2021-06-06 21:20 UTC
### Describe the issue
Plan fails to start-up with Java 16.

### Exceptions & Other Logs

```
[14:12:00] [Server thread/INFO]: [Plan] Loading Plan v5.3 build 1284
[14:12:00] [Server thread/INFO]: [Plan] Resolving runtime dependencies..
[14:12:00] [Server thread/INFO]: [Plan] Loading runtime dependencies..
[14:12:00] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Plan v5.3 build 1284 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at net.playeranalytics.plugin.dependencies.DependencyLoader.load(DependencyLoader.java:48) ~[?:?]
	at com.djrapitops.plan.DependencyStartup.loadDependencies(DependencyStartup.java:67) ~[?:?]
	at com.djrapitops.plan.Plan.onLoad(Plan.java:68) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7c7c7960
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at net.playeranalytics.plugin.ninja.egg82.mvn.classloaders.TransparentInjectableClassLoader.<clinit>(TransparentInjectableClassLoader.java:28) ~[?:?]
	... 8 more

```

```
[14:12:20] [Server thread/INFO]: [Plan] Processing complete.
[14:12:20] [Server thread/INFO]: [Plan] Waiting for unfinished transactions to avoid data loss..
[14:12:20] [Server thread/INFO]: [Plan] Transaction queue closed.
[14:12:20] [Server thread/INFO]: [Plan] Player Analytics Disabled.
[14:12:20] [Server thread/ERROR]: [Plan] Plan-v5.3 build 1284
java.lang.RuntimeException: Failed to load driver class plan.com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
	at plan.com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:491) ~[?:?]
	at com.djrapitops.plan.storage.database.MySQLDB.setupDataSource(MySQLDB.java:103) ~[?:?]
	at com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:108) ~[?:?]
	at com.djrapitops.plan.storage.database.DBSystem.enable(DBSystem.java:92) ~[?:?]
	at com.djrapitops.plan.storage.database.BukkitDBSystem.enable(BukkitDBSystem.java:58) ~[?:?]
	at com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:189) ~[?:?]
	at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:160) ~[?:?]
	at com.djrapitops.plan.Plan.onEnable(Plan.java:85) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:311) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[14:12:20] [Server thread/ERROR]: [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload
[14:12:20] [Server thread/ERROR]: [Plan] This error should be reported at https://github.com/plan-player-analytics/Plan/issues
[14:12:20] [Server thread/INFO]: [Plan] Processing complete.
[14:12:20] [Server thread/INFO]: [Plan] Player Analytics Disabled.
```

### Additional information
Java 16.0.1
MySQL

**Comment by Kopo942** [comment] 2021-06-06 21:25
Duplicate of #1886, check the issue for a workaround.

**Closed** 2021-06-07 09:41 UTC
Labels: Bug
