### ISSUE TITLE
Placeholders do not update

### ISSUE THREAD

**Issue by bimoluk** [plan-player-analytics/Plan#3632] opened 2024-05-19 15:56 UTC
Player placeholders do not update in real time, nor do other player's game times and kills. Only player death updates.

**Comment by AuroraLS3** [comment] 2024-05-19 16:06
Most of these placeholders are based on information from the database and database doesn't update in real time

**Comment by bimoluk** [comment] 2024-05-19 16:08
Is there any way to fix this? After adding the plan to the proxy, the game time placeholder also stopped updating, it previously worked

**Comment by AuroraLS3** [comment] 2024-05-19 16:13
Adding Plan to the proxy sounds unrelated.

Session related data: playtime, player kills, mob kills, deaths, world times data - these all update on player leave. This data can update for players who are on the same server, as live session from memory is added to the data, but update frequency depends on the other plugin replacing the placeholder.

I don't have a fix for this, it's working as designed - The level of detail available on the placeholders doesn't exceed that available on the website since they reuse the same code.

**Closed** 2024-06-15 06:42 UTC
Labels: Bug, Placeholders
