### ISSUE TITLE
это что то важное или можно забыть?

### ISSUE THREAD

**Issue by rkfsociety** [plan-player-analytics/Plan#1915] opened 2021-05-27 07:40 UTC
[org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Plan v5.3 build 1284 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at net.playeranalytics.plugin.dependencies.DependencyLoader.load(DependencyLoader.java:48) ~[?:?]
	at com.djrapitops.plan.DependencyStartup.loadDependencies(DependencyStartup.java:67) ~[?:?]
	at com.djrapitops.plan.Plan.onLoad(Plan.java:68) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:274) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @237c0d85
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at net.playeranalytics.plugin.ninja.egg82.mvn.classloaders.TransparentInjectableClassLoader.<clinit>(TransparentInjectableClassLoader.java:28) ~[?:?]
	... 8 more

**Comment by AuroraLS3** [comment] 2021-05-27 09:11
Duplicate of https://github.com/plan-player-analytics/Plan/issues/1886 - see ticket for `WORKAROUND`

**Closed by AuroraLS3** 2021-05-27 09:11 UTC
Labels: Bug
