### ISSUE TITLE
Default config.yml does not pass YAML validator

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#1499] opened 2020-06-20 05:21 UTC
### Describe the issue

Default config.yml does not pass [YAML validator](http://www.yamllint.com/).

### Server information

```
>version
[22:16:29] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a99063f-8ea9b13 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[22:16:29] [Server thread/INFO]: You are running the latest version
>version Plan
[22:16:33] [Server thread/INFO]: Plan version 5.1 build 615
[22:16:33] [Server thread/INFO]: Author: Rsl1122
```

![Screen Shot 2020-06-19 at 10 19 00 PM](https://user-images.githubusercontent.com/17748923/85193185-1c13c280-b27b-11ea-96cf-8846b47b2cc1.png)

**Comment by Rsl1122** [comment] 2020-06-20 05:33
Custom yml parser has been in use since 4.6.0, main difference is that yml spec doesn't allow keys with values to have children but some settings in Plan do. 
It has its downsides and move to a compliant format is going to happen at some point. 

Closing as duplicate of #1363

**Closed by Rsl1122** 2020-06-20 05:33 UTC
Labels: Bug
