### ISSUE TITLE
server overview

### ISSUE THREAD

**Issue by thunderlight411** [plan-player-analytics/Plan#1186] opened 2019-10-09 09:34 UTC
### Describe the issue

After installing Plan 5 on all the  servers everyting is working fine except t he Server > overview.
Got a black screen with onl7y the static information, no servers are showen as well online activity and the numbers

servers > sessions is working fine but there is no quick way to select a server in the overview to take a look on that specific system.

### Server information

Plan version 5
latest spigot and bungeecord release

**Comment by Rsl1122** [comment] 2019-10-09 09:36
Could you post a screenshot and also what is on the developer console (Ctrl+Shift+I > Console)

**Comment by Rsl1122** [comment] 2019-10-19 09:56
I suspect that the Bukkit/Sponge servers are not linked to the same MySQL database as BungeeCord. I am closing this issue since I don't have enough information to reproduce this issue.

If you would like this issue reopened, please send following information:
- Output of `planbungee servers` command
- Screenshot of the issue

**Closed by Rsl1122** 2019-10-19 09:56 UTC
Labels: note: Could not reproduce, note: Misconfiguration, status: Awaiting Reply
