### ISSUE TITLE
Litebans widget under players are broken

### ISSUE THREAD

**Issue by Cruwzky** [plan-player-analytics/Plan#2421] opened 2022-06-10 22:18 UTC
### Describe the issue
Under a player information -> Plugins -> Server 1 the Litebans widget is acting weird and is in this stage pretty useless.

It goes under the other widgets and it also cant really show any information because most of the under menus are not "scrollable".

I know there are other places to see the Litebans info, but it would be nice to also see it directly on the player.

### Exceptions & Other Logs
There are no error logs.

### Plugin versions
5.4 build 1690

### Additional information
![image](https://user-images.githubusercontent.com/20445289/173157679-f46adf00-0f0c-4a87-ad64-4c521bc275c0.png)

**Comment by AuroraLS3** [comment] 2022-06-11 04:28
Does this happen if you opt into Frontend Beta in the config?

**Comment by AuroraLS3** [comment] 2022-06-11 05:18
Looks like duplicate of #2180

**Comment by Cruwzky** [comment] 2022-06-11 08:34
Hi Aurora,

Sorry for the duplicate. It is the same issue.

And the beta opt does seem to fix it. Thanks!

**Comment by AuroraLS3** [comment] 2022-06-11 08:49
Thanks for confirmation

**Closed by AuroraLS3** 2022-06-11 08:49 UTC
Labels: Bug, Duplicate, status: Awaiting Reply
