### ISSUE TITLE
IllegalStateException: CapabilityService has not been initialised yet.

### ISSUE THREAD

**Issue by Fernthedev** [plan-player-analytics/Plan#1047] opened 2019-05-22 15:50 UTC
### Describe the bug
Not actually sure what's the cause, I just updated and randomly this happened. Guessing from the stacktrace, it's something with AdvancedBan

### Server information
Recent version of Waterfall and PaperSpigot
AdvancedBan Version 2.1.5-RELEASE

### Exceptions & Other Logs

Waterfall:
```java
[12:45:07 ERROR]: [global] Plan-v4.8.4
java.lang.IllegalStateException: CapabilityService has not been initialised yet.
        at com.djrapitops.plan.capability.CapabilityService.lambda$getInstance$0(CapabilityService.java:43) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_201]
        at com.djrapitops.plan.capability.CapabilityService.getInstance(CapabilityService.java:43) ~[?:?]
        at com.djrapitops.extension.AdvancedBanExtensionFactory.isAvailable(AdvancedBanExtensionFactory.java:40) ~[?:?]
        at com.djrapitops.extension.AdvancedBanExtensionFactory.createExtension(AdvancedBanExtensionFactory.java:47) ~[?:?]
        at com.djrapitops.plan.extension.implementation.ExtensionRegister.registerBuiltInExtensions(ExtensionRegister.java:45) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.enable(ExtensionServiceImplementation.java:84) ~[?:?]
        at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:140) ~[?:?]
        at com.djrapitops.plan.Plan.onEnable(Plan.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1613]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1613]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1613]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1613]
[12:45:07 ERROR]: [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload [12:45:07 ERROR]: [Plan] This error should be reported at https://github.com/Rsl1122/Plan-PlayerAnalytics/issues
```
PaperSpigot:
```java
java.lang.IllegalStateException: CapabilityService has not been initialised yet.
	at com.djrapitops.plan.capability.CapabilityService.lambda$getInstance$0(CapabilityService.java:43) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_201]
	at com.djrapitops.plan.capability.CapabilityService.getInstance(CapabilityService.java:43) ~[?:?]
	at com.djrapitops.extension.AdvancedBanExtensionFactory.isAvailable(AdvancedBanExtensionFactory.java:40) ~[?:?]
	at com.djrapitops.extension.AdvancedBanExtensionFactory.createExtension(AdvancedBanExtensionFactory.java:47) ~[?:?]
	at com.djrapitops.plan.extension.implementation.ExtensionRegister.registerBuiltInExtensions(ExtensionRegister.java:45) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.enable(ExtensionServiceImplementation.java:84) ~[?:?]
	at com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:140) ~[?:?]
	at com.djrapitops.plan.Plan.onEnable(Plan.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1613]
```

### Additional information
Advancedban is installed and functioning properly

**Frequency of occurrence**: <>
At startup, always.

**Comment by Rsl1122** [comment] 2019-05-28 17:10
Duplicate of #1041

**Closed by Rsl1122** 2019-05-28 17:10 UTC
Labels: Bug, DataExtensions
