### ISSUE TITLE
MYSQL/MARIADB Bug

### ISSUE THREAD

**Issue by Mitsu13Ion** [plan-player-analytics/Plan#1347] opened 2020-02-27 19:59 UTC
### Describe the issue

Error when i active mysql

### Serveur Information
**Plan Version:** 5.0 build 410
**Serveur:** Paper 1.15.2-R0.1-SNAPSHOT (git-Paper-118 (MC: 1.15.2))
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.19.0-6-amd64
**Java Version:** 11.0.6, Debian
**Java VM Version:** OpenJDK 64-Bit Serveur VM version 11.0.6+10-post-Debian-1deb10u1, Debian

### Benchmarks
```
488 ms     -124 MB Enable
17 ms      -2 MB   subsystem-enable



### Logged Errors

```
| 02-27 20:46:17 | java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: UPDATE plan_extension_user_values SET string_value=? WHERE uuid=? AND provider_id=(SELECT id FROM plan_extension_providers WHERE name=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=? LIMIT 1) LIMIT 1); Data truncation: Data too long for column 'string_value' at row 10
| 02-27 20:46:17 |    java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
| 02-27 20:46:17 |    java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
| 02-27 20:46:17 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
| 02-27 20:46:17 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 02-27 20:46:17 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 02-27 20:46:17 |    java.base/java.lang.Thread.run(Thread.java:834)
| 02-27 20:46:17 | Caused by:
| 02-27 20:46:17 | com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: UPDATE plan_extension_user_values SET string_value=? WHERE uuid=? AND provider_id=(SELECT id FROM plan_extension_providers WHERE name=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=? LIMIT 1) LIMIT 1); Data truncation: Data too long for column 'string_value' at row 10
| 02-27 20:46:17 |    com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:37)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:45)
| 02-27 20:46:17 |    com.djrapitops.plan.extension.implementation.storage.transactions.results.StoreJoueurStringResultTransaction.lambda$storeValue$0(StoreJoueurStringResultTransaction.java:63)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170)
| 02-27 20:46:17 |    com.djrapitops.plan.extension.implementation.storage.transactions.results.StoreJoueurStringResultTransaction.performOperations(StoreJoueurStringResultTransaction.java:58)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:246)
| 02-27 20:46:17 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 02-27 20:46:17 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 02-27 20:46:17 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 02-27 20:46:17 |    java.base/java.lang.Thread.run(Thread.java:834)
| 02-27 20:46:17 | Caused by:
| 02-27 20:46:17 | com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'string_value' at row 10
| 02-27 20:46:17 |    com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
| 02-27 20:46:17 |    com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
| 02-27 20:46:17 |    com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
| 02-27 20:46:17 |    com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
| 02-27 20:46:17 |    com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
| 02-27 20:46:17 |    com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
| 02-27 20:46:17 |    com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
| 02-27 20:46:17 |    com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2067)
| 02-27 20:46:17 |    com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5175)
| 02-27 20:46:17 |    com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2052)
| 02-27 20:46:17 |    plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
| 02-27 20:46:17 |    plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.transactions.ExecStatement.callExecute(ExecStatement.java:60)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42)
| 02-27 20:46:17 |    com.djrapitops.plan.extension.implementation.storage.transactions.results.StoreJoueurStringResultTransaction.lambda$storeValue$0(StoreJoueurStringResultTransaction.java:63)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170)
| 02-27 20:46:17 |    com.djrapitops.plan.extension.implementation.storage.transactions.results.StoreJoueurStringResultTransaction.performOperations(StoreJoueurStringResultTransaction.java:58)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:246)
| 02-27 20:46:17 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 02-27 20:46:17 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 02-27 20:46:17 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 02-27 20:46:17 |    java.base/java.lang.Thread.run(Thread.java:834)
| 02-27 20:46:17 |    com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:239)
| 02-27 20:46:17 |    com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:201)
| 02-27 20:46:17 |    com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:183)
| 02-27 20:46:17 |    com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:150)
| 02-27 20:46:17 |    com.djrapitops.plan.extension.ExtensionServiceImplementation.updateJoueurValues(ExtensionServiceImplementation.java:157)
| 02-27 20:46:17 |    com.djrapitops.plan.extension.ExtensionServiceImplementation.updateJoueurValues(ExtensionServiceImplementation.java:146)
| 02-27 20:46:17 |    com.djrapitops.plan.gathering.listeners.bukkit.JoueurOnlineListener.lambda$actOnJoinEvent$3(JoueurOnlineListener.java:189)
| 02-27 20:46:17 |    com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
| 02-27 20:46:17 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 02-27 20:46:17 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 02-27 20:46:17 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 02-27 20:46:17 |    java.base/java.lang.Thread.run(Thread.java:834)
```

```
| 02-27 20:48:20 | java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: UPDATE plan_extension_user_values SET string_value=? WHERE uuid=? AND provider_id=(SELECT id FROM plan_extension_providers WHERE name=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=? LIMIT 1) LIMIT 1); Data truncation: Data too long for column 'string_value' at row 10
| 02-27 20:48:20 |    java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
| 02-27 20:48:20 |    java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
| 02-27 20:48:20 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
| 02-27 20:48:20 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 02-27 20:48:20 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 02-27 20:48:20 |    java.base/java.lang.Thread.run(Thread.java:834)
| 02-27 20:48:20 | Caused by:
| 02-27 20:48:20 | com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: UPDATE plan_extension_user_values SET string_value=? WHERE uuid=? AND provider_id=(SELECT id FROM plan_extension_providers WHERE name=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=? LIMIT 1) LIMIT 1); Data truncation: Data too long for column 'string_value' at row 10
| 02-27 20:48:20 |    com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:37)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:45)
| 02-27 20:48:20 |    com.djrapitops.plan.extension.implementation.storage.transactions.results.StoreJoueurStringResultTransaction.lambda$storeValue$0(StoreJoueurStringResultTransaction.java:63)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170)
| 02-27 20:48:20 |    com.djrapitops.plan.extension.implementation.storage.transactions.results.StoreJoueurStringResultTransaction.performOperations(StoreJoueurStringResultTransaction.java:58)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:246)
| 02-27 20:48:20 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 02-27 20:48:20 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 02-27 20:48:20 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 02-27 20:48:20 |    java.base/java.lang.Thread.run(Thread.java:834)
| 02-27 20:48:20 | Caused by:
| 02-27 20:48:20 | com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'string_value' at row 10
| 02-27 20:48:20 |    com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
| 02-27 20:48:20 |    com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
| 02-27 20:48:20 |    com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
| 02-27 20:48:20 |    com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
| 02-27 20:48:20 |    com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
| 02-27 20:48:20 |    com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
| 02-27 20:48:20 |    com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
| 02-27 20:48:20 |    com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2067)
| 02-27 20:48:20 |    com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5175)
| 02-27 20:48:20 |    com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2052)
| 02-27 20:48:20 |    plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
| 02-27 20:48:20 |    plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.transactions.ExecStatement.callExecute(ExecStatement.java:60)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42)
| 02-27 20:48:20 |    com.djrapitops.plan.extension.implementation.storage.transactions.results.StoreJoueurStringResultTransaction.lambda$storeValue$0(StoreJoueurStringResultTransaction.java:63)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170)
| 02-27 20:48:20 |    com.djrapitops.plan.extension.implementation.storage.transactions.results.StoreJoueurStringResultTransaction.performOperations(StoreJoueurStringResultTransaction.java:58)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:246)
| 02-27 20:48:20 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 02-27 20:48:20 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 02-27 20:48:20 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 02-27 20:48:20 |    java.base/java.lang.Thread.run(Thread.java:834)
| 02-27 20:48:20 |    com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:239)
| 02-27 20:48:20 |    com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:201)
| 02-27 20:48:20 |    com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:183)
| 02-27 20:48:20 |    com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:150)
| 02-27 20:48:20 |    com.djrapitops.plan.extension.ExtensionServiceImplementation.updateJoueurValues(ExtensionServiceImplementation.java:157)
| 02-27 20:48:20 |    com.djrapitops.plan.extension.ExtensionServiceImplementation.updateJoueurValues(ExtensionServiceImplementation.java:146)
| 02-27 20:48:20 |    com.djrapitops.plan.gathering.listeners.bukkit.JoueurOnlineListener.lambda$beforeJoueurQuit$5(JoueurOnlineListener.java:200)
| 02-27 20:48:20 |    com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
| 02-27 20:48:20 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 02-27 20:48:20 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 02-27 20:48:20 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 02-27 20:48:20 |    java.base/java.lang.Thread.run(Thread.java:834)
```


### Additional information
paper-118 1.15.2

**Comment by Rsl1122** [comment] 2020-02-27 20:59
Duplicate of #1333 

Fixed in build 415
https://github.com/plan-player-analytics/Plan/releases/tag/5.0.415

**Closed by Rsl1122** 2020-02-27 20:59 UTC
