### ISSUE TITLE
Error was caught by com.djrapitops.plan.PlanBungee

### ISSUE THREAD

**Issue by xXSchrandXx** [plan-player-analytics/Plan#1048] opened 2019-05-26 06:52 UTC
### Describe the bug

Webserver doesn't startup:
``` LOG
[08:40:38] [Plan/INFO] > Locale: 'Deutch' by Eyremba & fuzzlemann & Morsmorse
[08:40:38] [Plan/INFO] > Du verwendest die neuste Version
[08:40:38] [Plan/INFO] > MySQL-dDatenbankverbindung hergestellt.
[08:40:38] [Plan/INFO] > Certificate: X.509
[08:40:38] [Plan/INFO] > Webserver läuft auf PORT 8804 (https://leaderboard.ragebears.de:8804)
[08:40:38] [Plan/ERROR] > Error was caught by com.djrapitops.plan.PlanBungee
[08:40:38] [Plan/ERROR] > CRITICAL error triggered a plugin shutdown.
[08:40:38] [Plan/INFO] > Verarbeite kritische unverarbeitete Aufgaben. (0)
[08:40:38] [Plan/INFO] > Verarbeitung komplett.
[08:40:38] [Plan/INFO] > Webserver deaktiviert.
[08:40:38] [Plan/INFO] > Player Analytics ausgeschaltet.
[08:40:38] [Plan/ERROR] > Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /planbungee reload
[08:40:38] [Plan/ERROR] > This error should be reported at https://github.com/Rsl1122/Plan-PlayerAnalytics/issues
[08:40:38] [Plan/INFO] > Verarbeite kritische unverarbeitete Aufgaben. (0)
[08:40:38] [Plan/INFO] > Verarbeitung komplett.
[08:40:38] [Plan/INFO] > Webserver deaktiviert.
[08:40:38] [Plan/INFO] > Player Analytics ausgeschaltet.
```

### Errors

``` LOG
[08:45:59] [BungeeCord/INFO] > These are the platforms and versions that are used to run GalaxiBungee:
[08:45:59] [BungeeCord/INFO] >   Linux 3.16.0-4-amd64 [x64],
[08:45:59] [BungeeCord/INFO] >   Java 1.8.0_191 [x64],
[08:45:59] [BungeeCord/INFO] >   GalaxiEngine v3.2.0c (19w21a),
[08:45:59] [BungeeCord/INFO] >   GalaxiBungee v1.14a (19w21c)
```

### Exceptions & Other Logs

``` LOG
| 05-26 08:40:38 | com.djrapitops.plan.PlanBungee caught IllegalStateException
| 05-26 08:40:38 | java.lang.IllegalStateException: CapabilityService has not been initialised yet.
| 05-26 08:40:38 |    com.djrapitops.plan.capability.CapabilityService.lambda$getInstance$0(CapabilityService.java:43)
| 05-26 08:40:38 |    java.util.Optional.orElseThrow(Optional.java:290)
| 05-26 08:40:38 |    com.djrapitops.plan.capability.CapabilityService.getInstance(CapabilityService.java:43)
| 05-26 08:40:38 |    com.djrapitops.extension.AdvancedBanExtensionFactory.isAvailable(AdvancedBanExtensionFactory.java:40)
| 05-26 08:40:38 |    com.djrapitops.extension.AdvancedBanExtensionFactory.createExtension(AdvancedBanExtensionFactory.java:47)
| 05-26 08:40:38 |    com.djrapitops.plan.extension.implementation.ExtensionRegister.registerBuiltInExtensions(ExtensionRegister.java:45)
| 05-26 08:40:38 |    com.djrapitops.plan.extension.ExtensionServiceImplementation.enable(ExtensionServiceImplementation.java:84)
| 05-26 08:40:38 |    com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:140)
| 05-26 08:40:38 |    com.djrapitops.plan.PlanBungee.onEnable(PlanBungee.java:47)
| 05-26 08:40:38 |    net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
| 05-26 08:40:38 |    net.md_5.bungee.BungeeCord.start(BungeeCord.java:302)
| 05-26 08:40:38 |    net.ME1312.SubServers.Bungee.Launch.main(Launch.java:127)
```

**Comment by Rsl1122** [comment] 2019-05-28 17:09
Duplicate of #1047

**Closed by Rsl1122** 2019-05-28 17:09 UTC
Labels: Bug, DataExtensions

**Comment by Rsl1122** [comment] 2019-05-28 17:11
Duplicate of #1041
