### ISSUE TITLE
Console Error Not Working

### ISSUE THREAD

**Issue by Teals53** [plan-player-analytics/Plan#1902] opened 2021-05-18 23:19 UTC
[23:18:34 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Plan v5.3 build 1284 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at net.playeranalytics.plugin.dependencies.DependencyLoader.load(DependencyLoader.java:48) ~[?:?]
        at com.djrapitops.plan.DependencyStartup.loadDependencies(DependencyStartup.java:67) ~[?:?]
        at com.djrapitops.plan.Plan.onLoad(Plan.java:68) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-703]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @208ad191
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at net.playeranalytics.plugin.ninja.egg82.mvn.classloaders.TransparentInjectableClassLoader.<clinit>(TransparentInjectableClassLoader.java:28) ~[?:?]
        ... 8 more

**Comment by Teals53** [comment] 2021-05-18 23:25
add java 16 support thx

**Comment by Kopo942** [comment] 2021-05-18 23:35
Duplicate of #1886, Java 16 isn't supported yet.

**Comment by AuroraLS3** [comment] 2021-05-19 04:49
Follow issue Kopo942 linked for resolution

**Closed** 2021-05-19 04:49 UTC
Labels: Bug, Duplicate
