### ISSUE TITLE
java.lang.NoSuchMethodError: net.md_5.bungee.api.chat.ComponentBuilder.appendLegacy(Ljava/lang/String;)Lnet/md_5/bungee/api/chat/ComponentBuilder; on 1.12.2

### ISSUE THREAD

**Issue by AntonUden** [plan-player-analytics/Plan#1613] opened 2020-10-18 19:51 UTC
### Describe the issue
Getting a java.lang.NoSuchMethodError when trying to use any plan commands

### Server information
Plan v5.1 build 770
Got the error on both
CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) (from /version)
and
Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) (from /version)

### Exceptions & Other Logs
```
java.lang.NoSuchMethodError: net.md_5.bungee.api.chat.ComponentBuilder.appendLegacy(Ljava/lang/String;)Lnet/md_5/bungee/api/chat/ComponentBuilder;
        at com.djrapitops.plan.commands.use.BukkitPartBuilder.addPart(BukkitPartBuilder.java:46) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onHelp(CommandWithSubcommands.java:57) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:114) ~[?:?]
        at com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:84) ~[?:?]
        at com.djrapitops.plan.commands.use.BukkitCommand$1.run(BukkitCommand.java:60) ~[?:?]
        at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

**Comment by Rsl1122** [comment] 2020-10-19 06:01
Duplicate of #1600

**Closed by Rsl1122** 2020-10-19 06:01 UTC
Labels: Bug
