### ISSUE TITLE
Saving not connected player data

### ISSUE THREAD

**Issue by haeiven** [plan-player-analytics/Plan#1218] opened 2019-11-10 18:52 UTC
### Describe the issue

Plan is saving data for players who never joined the network, like bots who was denied to join.

### Server information

Latest Waterfall version, with Plan Build 279

### Exceptions & Other Logs

/

### Additional information

Plan shouldn't save this data, it's registering useless players in the database.

**Comment by Rsl1122** [comment] 2019-11-10 19:01
How to distinguish between a user and a bot?

**Comment by haeiven** [comment] 2019-11-10 22:05
If the login event was cancelled, it should not add the player to the database ^^

**Comment by Rsl1122** [comment] 2019-11-10 22:20
Duplicate of #758 - Follow the issue for resolution to this one.

**Closed** 2019-11-10 22:20 UTC
Labels: Duplicate
