### ISSUE TITLE
MySQL errors when updating plan_extension_user_values

### ISSUE THREAD

**Issue by metalshark** [plan-player-analytics/Plan#1338] opened 2020-02-16 06:57 UTC
### Describe the issue
Am receiving a large number of errors in the console related to plan.

### Server information
Paper 1.15.2 #105. MySQL 5.6. Plan v5.0 Build 410.

### Exceptions & Other Logs
[12:28:27] [Plan MySQLDB-transaction-thread-1/ERROR]: [Plan] Error was caught by com.djrapitops.plan.storage.database.MySQLDB
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: UPDATE plan_extension_user_values SET string_value=? WHERE uuid=? AND provider_id=(SELECT id FROM plan_extension_providers WHERE name=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=? LIMIT 1) LIMIT 1); Data truncation: Data too long for column 'string_value' at row 9
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: UPDATE plan_extension_user_values SET string_value=? WHERE uuid=? AND provider_id=(SELECT id FROM plan_extension_providers WHERE name=? AND plugin_id=(SELECT id FROM plan_extension_plugins WHERE name=? AND server_uuid=? LIMIT 1) LIMIT 1); Data truncation: Data too long for column 'string_value' at row 9
	at com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:37) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:45) ~[?:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerStringResultTransaction.lambda$storeValue$0(StorePlayerStringResultTransaction.java:63) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[?:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerStringResultTransaction.performOperations(StorePlayerStringResultTransaction.java:58) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[?:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:246) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	... 3 more
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'string_value' at row 9
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2067) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5175) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2052) ~[patched_1.15.2.jar:git-Paper-df0d7b0d]
	at plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
	at plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.callExecute(ExecStatement.java:60) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42) ~[?:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerStringResultTransaction.lambda$storeValue$0(StorePlayerStringResultTransaction.java:63) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:170) ~[?:?]
	at com.djrapitops.plan.extension.implementation.storage.transactions.results.StorePlayerStringResultTransaction.performOperations(StorePlayerStringResultTransaction.java:58) ~[?:?]
	at com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:72) ~[?:?]
	at com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:246) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
	at com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:239) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:201) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:183) ~[?:?]
	at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:150) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updatePlayerValues(ExtensionServiceImplementation.java:157) ~[?:?]
	at com.djrapitops.plan.extension.ExtensionServiceImplementation.updatePlayerValues(ExtensionServiceImplementation.java:146) ~[?:?]
	at com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener.lambda$actOnJoinEvent$3(PlayerOnlineListener.java:189) ~[?:?]
	at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	... 3 more

### Additional information
We run the server in online mode and use CMI for nickname functionality. This includes the use of unicode characters in nicknames and EmojiChat support (so a utf8mb4 character set).

**Comment by Rsl1122** [comment] 2020-02-16 11:20
Duplicate of #1333 See that issue for temporary solution & follow the issue for resolution.

**Closed by Rsl1122** 2020-02-16 11:20 UTC

**Comment by metalshark** [comment] 2020-02-20 06:35
The DiscordSRV extension is the one causing this.
