### ISSUE TITLE
Locale on BungeeCord does not affect server pages

### ISSUE THREAD

**Issue by Sprungente** [plan-player-analytics/Plan#785] opened 2018-11-10 16:06 UTC
### Describe the bug
The Serverhealthpage, the part with the last 30 days, translations don't work for Servers (if with Bungeecord)

### Server information
1.13.2 Spigot ; Plan 4.5.1

### Exceptions & Other Logs
no

### Additional information
Running a bungeecordnetwork. Only minecraftserver are affect

**Frequency of occurrence**: <>

**Other:**

**Comment by Rsl1122** [comment] 2018-11-11 10:47
I think I misunderstood the issue before - So the issue is that the server pages' server health tab is not translated when the locale is in use on BungeeCord, correct?

Currently the locale setting or file is not transferred to the other servers. Server pages are generated on the other servers - So they don't have access to the locale.

----

Temporary solution until locale is shared between servers is to have the same locale on all servers

**Comment by Rsl1122** [comment] 2019-10-17 20:13
Fixed in 5.0

**Closed by Rsl1122** 2019-10-17 20:13 UTC
Labels: Enhancement, Temporary Fix Available, p: 13, server: Networks
