### ISSUE TITLE
LuckPerms 5.0.92 and Plan 5.0 build 415 causing Error

### ISSUE THREAD

**Issue by macy2fast** [plan-player-analytics/Plan#1359] opened 2020-03-12 04:30 UTC
### Describe the issue
LuckPerms 5.0.92 and Plan 5.0 build 415 causing Error:

22:22:05] [Velocity Task Scheduler - #0/INFO]: Registered extension: LuckPerms
[22:22:05] [Plan Non critical-pool-2/WARN]: Encountered IllegalArgumentException with LuckPerms Extension (failed safely) when updating value for 'server', the method was disabled temporarily (won't be called until next Plan reload), stack trace to follow (please report this):
[22:22:05] [Plan Non critical-pool-2/WARN]: Error was caught by com.djrapitops.plan.extension.ExtensionServiceImplementation
java.lang.IllegalArgumentException: class com.djrapitops.extension.LuckPermsExtension method tracks could not be called: null

Seems like a possible Regression from: IllegalArgumentException with latest LuckPerms/ExtraContexts #1236 https://github.com/plan-player-analytics/Plan/issues/1236

### Server information
**Plan Version:** 5.0 build 415
**Server:** Velocity 1.0.5-SNAPSHOT (git-0c7a9957-b190) (1.0.5-SNAPSHOT (git-0c7a9957-b190))
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 5.0.0-1031-azure
**Java Version:** 11.0.6, Ubuntu
**Java VM Version:** OpenJDK 64-Bit Server VM version 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, Ubuntu
### Benchmarks
```
177 ms     -821 KB subsystem-enable
```

### Exceptions & Other Logs

```
 03-11 22:19:22 |    com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
| 03-11 22:19:22 |    java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
| 03-11 22:19:22 |    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
| 03-11 22:19:22 |    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
| 03-11 22:19:22 |    java.base/java.lang.Thread.run(Thread.java:834)
```
```
| 03-11 22:19:22 | java.lang.IllegalArgumentException: class com.djrapitops.extension.LuckPermsExtension method tracks could not be called: null
| 03-11 22:19:22 |    com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:51)
| 03-11 22:19:22 |    com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.lambda$null$3(TableProviderValueGatherer.java:82)
| 03-11 22:19:22 |    com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.getMethodResult(TableProviderValueGatherer.java:119)
| 03-11 22:19:22 |    com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfProvider(TableProviderValueGatherer.java:103)
| 03-11 22:19:22 |    com.djrapitops.plan.extension.implementation.providers.gathering.TableProviderValueGatherer.gatherTableDataOfServer(TableProviderValueGatherer.java:86)
| 03-11 22:19:22 |    com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:162)
```

### Additional information
Removing the luckperms-velocity-5.0.92 jar from plugins resolves the issue

**Comment by Rsl1122** [comment] 2020-03-12 06:18
The exception stacktrace is cut short - please include the full stacktrace (caused by is important)

**Comment by Rsl1122** [comment] 2020-03-12 06:32
Stacktrace from another user from Discord
https://pastebin.com/raw/biMpiCWa

**Comment by Rsl1122** [comment] 2020-03-26 09:32
Sort-of fixed by Luck. Instead of this error, Luckperms Extension will fail to register sometimes.

**Closed by Rsl1122** 2020-03-26 09:32 UTC
Labels: Bug, DataExtensions
