### ISSUE TITLE
Warn spam

### ISSUE THREAD

**Issue by flantertw** [plan-player-analytics/Plan#1065] opened 2019-06-03 17:07 UTC
### Describe the bug

When I updated to the latest version of the spigot, 2-3 minutes after starting the server, it starts spamming with such errors with a frequency of 3 seconds.

### Server information

Plugin version: latest
Spigot build: latest (git-Spigot-baafee9-043d31d (MC: 1.14.2))

### Exceptions & Other Logs

[Server thread/WARN]: [Plan] Task #45 for Plan v4.8.5 generated an exception
java.lang.IllegalAccessError: tried to access field net.minecraft.server.v1_14_R1.Entity.bukkitEntity from class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand
	at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand.getBukkitEntity(EntityNMSArmorStand.java:206) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getEntities(CraftWorld.java:815) ~[core.jar:git-Spigot-baafee9-043d31d]
	at com.djrapitops.plan.system.tasks.bukkit.BukkitTPSCountTimer.getEntityCount(BukkitTPSCountTimer.java:150) ~[?:?]
	at com.djrapitops.plan.system.tasks.bukkit.BukkitTPSCountTimer.calculateTPS(BukkitTPSCountTimer.java:85) ~[?:?]
	at com.djrapitops.plan.system.tasks.bukkit.BukkitTPSCountTimer.addNewTPSEntry(BukkitTPSCountTimer.java:67) ~[?:?]
	at com.djrapitops.plan.system.tasks.TPSCountTimer.run(TPSCountTimer.java:71) ~[?:?]
	at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[core.jar:git-Spigot-baafee9-043d31d]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [core.jar:git-Spigot-baafee9-043d31d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

### Additional information

**Frequency of occurrence**: <>

**Other:**

**Comment by Rsl1122** [comment] 2019-06-03 17:12
Duplicate of #1064 

This issue is something to do with HolographicDisplays, I can't fix this.

**Closed by Rsl1122** 2019-06-03 17:12 UTC
