### ISSUE TITLE
H2 Database Init Failure

### ISSUE THREAD

**Issue by good777LUCKY** [plan-player-analytics/Plan#1462] opened 2020-05-26 07:52 UTC
### Describe the issue

I have been changed database h2 to mysql, and I changed ot to h2 again. I don't delete h2 database but it says 'Error: H2 init failure: (Message 28000 not found) [28000-119]' Also I try /plan reload, it will show same error.

### Server information

`Database it closed. Try it later.`
I am using build 563, in Nukkit platform.

### Exceptions & Other Logs

`Error: H2 init failure: (Message 28000 not found) [28000-119]`

**Comment by Rsl1122** [comment] 2020-05-26 15:45
28000 error code says "WRONG USER OR PASSWORD"

If you have changed the database settings (password and user) from defaults then that is the cause since H2 uses the same user/pass fields
See https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/config.yml#L32 for default values

**Comment by good777LUCKY** [comment] 2020-05-26 16:34
I thought H2 database config doesn't use MySQL's username and password config.

**Comment by Rsl1122** [comment] 2020-05-26 16:43
It unfortunately does because it was merged that way and now it is too late to change to not break existing databases

**Closed** 2020-05-26 17:44 UTC
Labels: Bug
