### ISSUE TITLE
Encountered IllegalArgumentException with DiscordSRV

### ISSUE THREAD

**Issue by RalphORama** [plan-player-analytics/Plan#1224] opened 2019-11-15 03:44 UTC
### Describe the issue

I get this error in console when I have Plan and DiscordSRV together.  Just shows up in console, not because of any discernible event

### Server information

- Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
- Plan 5.0 build 279
- DiscordSRV build 1.8.1

### Exceptions & Other Logs

```
[03:36:27 WARN]: [Plan] Encountered IllegalArgumentException with DiscordSRV Extension (failed safely) when updating value for 'server', the method was disabled temporarily (won't be called until next Plan reload), stack trace to follow (please report this):
[03:36:27 WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.ExtensionServiceImplementation
java.lang.IllegalArgumentException: class com.djrapitops.extension.DiscordSRVExtension method accountsLinkedPerMembers could not be called: null
at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:85) ~[?:?]
at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:64) ~[?:?]
at com.djrapitops.plan.extension.implementation.providers.gathering.DoubleAndPercentageProviderValueGatherer.lambda$null$4(DoubleAndPercentageProviderValueGatherer.java:82) ~[?:?]
at com.djrapitops.plan.extension.implementation.providers.gathering.DoubleAndPercentageProviderValueGatherer.getMethodResult(DoubleAndPercentageProviderValueGatherer.java:122) ~[?:?]
at com.djrapitops.plan.extension.implementation.providers.gathering.DoubleAndPercentageProviderValueGatherer.gatherDoubleDataOfProvider(DoubleAndPercentageProviderValueGatherer.java:105) ~[?:?]
at com.djrapitops.plan.extension.implementation.providers.gathering.DoubleAndPercentageProviderValueGatherer.gatherDoubleDataOfServer(DoubleAndPercentageProviderValueGatherer.java:87) ~[?:?]
at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:142) ~[?:?]
at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:198) ~[?:?]
at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:205) ~[?:?]
at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:185) ~[?:?]
at com.djrapitops.plan.extension.ExtensionServerMethodCallerTask.run(ExtensionServerMethodCallerTask.java:41) ~[?:?]
at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-226]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-226]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:71) ~[?:?]
... 17 more
Caused by: java.lang.NoSuchMethodError: github.scarsz.discordsrv.DiscordSRV.getMainGuild()Lgithub/scarsz/discordsrv/dependencies/jda/core/entities/Guild;
at com.djrapitops.extension.DiscordSRVExtension.getMainGuild(DiscordSRVExtension.java:76) ~[?:?]
at com.djrapitops.extension.DiscordSRVExtension.getGuildMemberCount(DiscordSRVExtension.java:90) ~[?:?]
at com.djrapitops.extension.DiscordSRVExtension.accountsLinkedPerMembers(DiscordSRVExtension.java:232) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:71) ~[?:?]
... 17 more
```

### Additional information

N/A

**Comment by Rsl1122** [comment] 2019-11-15 06:55
Duplicate of #1221 See the issue for resolution

**Closed by Rsl1122** 2019-11-15 06:55 UTC
