### ISSUE TITLE
CraftingStore Plugin Integration

### ISSUE THREAD

**Issue by Tactryl3** [plan-player-analytics/Plan#1981] opened 2021-07-05 19:23 UTC
### Data to display

Ranks Purchased, Total $ donated, etc. 
I'm not sure what you have for Buycraft/Tebex, but I would assume the information they provide is similar. 

### Plugin information

**API or Source Code:** https://github.com/CraftingStore/MinecraftPlugin

**Project page or Downloads:** https://craftingstore.net/

**Comment by AuroraLS3** [comment] 2021-07-05 19:25
Duplicate of  #1917

**Closed by AuroraLS3** 2021-07-05 19:25 UTC
Labels: DataExtensions, Help Wanted, New Data
