### ISSUE TITLE
Server details of uninstalled Server are copied over on DB move

### ISSUE THREAD

**Issue by Mareron** [plan-player-analytics/Plan#2050] opened 2021-08-12 16:02 UTC
I'm trying to switch from SQLite to MySQL.
When I'm running plan db move SQLite MySQL I'm getting the following Error after a minute or two:

```
37793b53d8 - Last occurred: 2021-08-12 Occurrences: 1
---- Context 1 ----
Plan v5.4 build 1366
Sponge 1.12.2
Server v1.12.2

Transaction: class com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction
DB State: OPEN
Error code: 1048
INSERT INTO plan_tps (server_id,date,tps,players_online,cpu_usage,ram_usage,entities,chunks_loaded,free_disk_space) VALUES ((SELECT plan_servers.id FROM plan_servers WHERE plan_servers.uuid=? LIMIT 1),?, ?, ?, ?, ?, ?, ?, ?)
Unknown SQL Error code

---- Stacktrace ----
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Column 'server_id' cannot be null
   java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
   java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Column 'server_id' cannot be null
   com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:135)
   com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:45)
   com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:207)
   com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction.copy(BackupCopyTransaction.java:67)
   com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction.copyTPSData(BackupCopyTransaction.java:91)
   com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction.performOperations(BackupCopyTransaction.java:56)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:82)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:264)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
java.sql.BatchUpdateException: Column 'server_id' cannot be null
   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   plan.com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
   plan.com.mysql.cj.util.Util.getInstance(Util.java:167)
   plan.com.mysql.cj.util.Util.getInstance(Util.java:174)
   plan.com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executePreparedBatchAsMultiStatement(ClientPreparedStatement.java:584)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:431)
   plan.com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
   plan.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
   plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
   com.djrapitops.plan.storage.database.transactions.ExecBatchStatement.callExecute(ExecBatchStatement.java:35)
   com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52)
   com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42)
   com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:207)
   com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction.copy(BackupCopyTransaction.java:67)
   com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction.copyTPSData(BackupCopyTransaction.java:91)
   com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction.performOperations(BackupCopyTransaction.java:56)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:82)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:264)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
java.sql.SQLIntegrityConstraintViolationException: Column 'server_id' cannot be null
   plan.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
   plan.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executePreparedBatchAsMultiStatement(ClientPreparedStatement.java:512)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:431)
   plan.com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
   plan.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
   plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
   com.djrapitops.plan.storage.database.transactions.ExecBatchStatement.callExecute(ExecBatchStatement.java:35)
   com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52)
   com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42)
   com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:207)
   com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction.copy(BackupCopyTransaction.java:67)
   com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction.copyTPSData(BackupCopyTransaction.java:91)
   com.djrapitops.plan.storage.database.transactions.BackupCopyTransaction.performOperations(BackupCopyTransaction.java:56)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:82)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:264)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
   com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:260)
   com.djrapitops.plan.commands.subcommands.DatabaseCommands.performMove(DatabaseCommands.java:256)
   com.djrapitops.plan.commands.subcommands.DatabaseCommands.lambda$onMove$4(DatabaseCommands.java:240)
   com.djrapitops.plan.commands.subcommands.Confirmation.onConfirm(Confirmation.java:55)
   com.djrapitops.plan.commands.subcommands.Confirmation.onAcceptCommand(Confirmation.java:78)
   com.djrapitops.plan.commands.use.SubcommandBuilder.lambda$onCommand$0(SubcommandBuilder.java:54)
   com.djrapitops.plan.commands.use.CommandWithSubcommands.executeCommand(CommandWithSubcommands.java:106)
   com.djrapitops.plan.commands.use.CommandWithSubcommands.onCommand(CommandWithSubcommands.java:83)
   com.djrapitops.plan.commands.use.SpongeCommand.lambda$process$0(SpongeCommand.java:55)
   org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
   org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197)
   java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   java.util.concurrent.FutureTask.run(FutureTask.java:266)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
```

**Comment by AuroraLS3** [comment] 2021-08-12 17:58
Additional details:

- Caused by the backup transaction using the server listing query that doesn't include servers marked as uninstalled. (This leads to the server missing from plan_servers while data for that id is attempted to be inserted)

**Closed** 2021-09-10 15:33 UTC
Labels: Bug, p: 1
