### ISSUE TITLE
"Plan" is most overloaded plugin on server

### ISSUE THREAD

**Issue by iBars** [plan-player-analytics/Plan#1390] opened 2020-04-03 03:26 UTC
### Describe the issue
Spigot `/timings` tells about Plan is most overloaded plugin on server, his Scheduled tasks are take many server resources and cause low TPS:

![image](https://user-images.githubusercontent.com/3519015/78320948-67b7a980-7573-11ea-8239-abcc85601e5a.png)

![image](https://user-images.githubusercontent.com/3519015/78320980-7900b600-7573-11ea-9db7-ed0cbbdf561b.png)

### Server information
Latest Plan v5.1 b497 _`(also tested v5.0 b309)`_

### Additional information
Tested on Spigot 1.12.2/1.14.4/1.15.2 and Paper 1.15.2

**Comment by Rsl1122** [comment] 2020-04-03 06:50
Duplicate of #1364

Please install Spark and run `spark sampler --only-ticks-over 55` for a while, and then stop the profiling - This is to find out the actual cause of the issue.
https://www.spigotmc.org/resources/spark.57242/

Please post it in issue #1364 as a comment

**Closed by Rsl1122** 2020-04-03 06:50 UTC
Labels: Bug

**Comment by Rsl1122** [comment] 2020-04-03 07:07
You might also want to apply the suggested remedy of disabling disk space gathering in the config
