### ISSUE TITLE
Suggestion: Add Java 16 support

### ISSUE THREAD

**Issue by 10935336** [plan-player-analytics/Plan#1905] opened 2021-05-20 13:02 UTC
### Is your feature request related to a problem? Please describe.

Yes, I cannot use Plan in Java 16.
Why? Because Paper has required Java 16 in 1.16.5 build 669, and Minecraft will also require Java 16 in 1.17, it seems reasonable to do related work in advance.

```
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Please update the version of Java you use to run Paper
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] * to at least Java 16. When Paper for Minecraft 1.17 is
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] * released support for versions of Java before 16 will
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] * be dropped.
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Current Java version: 15.0.3
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] *
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] * Check this forum post for more information: 
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] *   https://papermc.io/java16
[20:52:51 WARN]: [io.papermc.paper.util.PaperJvmChecker] ************************************************************
```

Using Java 16 in the current version results in the following error. 
Server type: Paper 1.16.5 Build 705
Plan version: Plan-v5.3 build 1284
Java version: zulu16.30.15-ca-fx-jdk16.0.1-linux_x64

```
[Plan] Plan-v5.3 build 1284
java.lang.RuntimeException: Failed to load driver class plan.com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at plan.com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:491) ~[?:?]
        at com.djrapitops.plan.storage.database.MySQLDB.setupDataSource(MySQLDB.java:103) ~[?:?]
        at com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:108) ~[?:?]
        at com.djrapitops.plan.storage.database.DBSystem.enable(DBSystem.java:92) ~[?:?]
        at com.djrapitops.plan.storage.database.BukkitDBSystem.enable(BukkitDBSystem.java:58) ~[?:?]
        at com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:189) ~[?:?]
        at com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:160) ~[?:?]
        at com.djrapitops.plan.Plan.onEnable(Plan.java:85) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-"2c6b1f048"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.16.5.jar:git-Paper-"2c6b1f048"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:495) ~[patched_1.16.5.jar:git-Paper-"2c6b1f048"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-"2c6b1f048"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-"2c6b1f048"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-"2c6b1f048"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-"2c6b1f048"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-"2c6b1f048"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-"2c6b1f048"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### I would like to be able to..
Add Java 16 support.

**Comment by AuroraLS3** [comment] 2021-05-20 13:28
Duplicate of  #1886 - See that issue for temporary solution to use until this is fixed

**Closed by AuroraLS3** 2021-05-20 13:28 UTC
