### ISSUE TITLE
WaterdogPE support

### ISSUE THREAD

**Issue by xxFLORII** [plan-player-analytics/Plan#3031] opened 2023-05-21 08:08 UTC
### I would like to be able to..

Please add WaterdogPE as proxy software in addition to Bungeecord/Velocity support.

### Is your feature request related to a problem? Please describe.

No, it isn‘t

**Comment by AuroraLS3** [comment] 2023-05-21 08:21
Duplicate of https://github.com/plan-player-analytics/Plan/issues/2771

**Closed by AuroraLS3** 2023-05-21 08:21 UTC
