### ISSUE TITLE
Folia Support

### ISSUE THREAD

**Issue by mddewittjr** [plan-player-analytics/Plan#3239] opened 2023-10-02 00:40 UTC
### I would like to be able to..

Add the ability to support folia. 

### Is your feature request related to a problem? Please describe.

Yes, currently not supported by folia 1.20.1

**Comment by AuroraLS3** [comment] 2023-10-02 05:20
Duplicate of  #2962

**Closed by AuroraLS3** 2023-10-02 05:20 UTC

**Comment by mddewittjr** [comment] 2023-10-15 03:30
Oh my bad.  Just saw the other one by qbasty.
