### ISSUE TITLE
Plan Throwing Errors on Player Quit

### ISSUE THREAD

**Issue by bipedd** [plan-player-analytics/Plan#3112] opened 2023-07-09 20:51 UTC
### Describe the issue

When players quit errors pop up in my console, see below

### Exceptions & Other Logs

plugins/Plan/logs:
 https://mclo.gs/Rg4t2nj

```
Console error: https://mclo.gs/TkUuVcG
```

### Plugin versions

Plan 5.5 Build 2391
### Additional information

Tried uninstalling the plugin and reinstalling, as well as regenerating folder

**Comment by AuroraLS3** [comment] 2023-07-10 04:05
Duplicate of https://github.com/plan-player-analytics/Plan/issues/3098 - downgrade to paper 62

**Closed by AuroraLS3** 2023-07-10 04:05 UTC
Labels: Bug
