### ISSUE TITLE
Plan Bungee Error

### ISSUE THREAD

**Issue by w41k3r26** [plan-player-analytics/Plan#1636] opened 2020-11-04 11:41 UTC
I recently migrated to a closer location node. I tried setting up plan after updating to 1.16.4 and got this error.

```
java.lang.NullPointerException | /
    com.djrapitops.plan.delivery.webserver.resolver.RootPageResolver.getResponse(RootPageResolver.java:63)
    com.djrapitops.plan.delivery.webserver.resolver.RootPageResolver.resolve(RootPageResolver.java:57)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:187)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:138)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:134)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)```

**Comment by Rsl1122** [comment] 2020-11-04 11:43
Duplicate of #1478

This occurs when Plan has enabled the webserver but has not completely enabled yet.

**Closed by Rsl1122** 2020-11-04 11:43 UTC
