### ISSUE TITLE
Litebans, and Sessions update slow or don't do it at all

### ISSUE THREAD

**Issue by ZeroTwoO2** [plan-player-analytics/Plan#3109] opened 2023-07-09 13:29 UTC
### Describe the issue

Once a player joins the server, I wait 5 minutes to see if the session length has been updated. But it doesn't. As of litebans, a player gets banned but it either doesn't show on the web interface, or does in like 15-30 minutes.

### Exceptions & Other Logs

```

```

### Plugin versions

Litebans - LiteBans 2.12.4
Plan - Player Analytics 5.5 build 2391

### Additional information

I've tried multiple things. Restarting the server, waiting longer, trying the change configs, but it doesn't really work

**Comment by ZeroTwoO2** [comment] 2023-07-09 13:30
Also ping does this aswell

**Comment by AuroraLS3** [comment] 2023-07-09 14:30
Are you using export by any chance?

**Comment by AuroraLS3** [comment] 2023-07-09 14:39
Session issue solved on discord.

Litebans issue duplicate of https://github.com/plan-player-analytics/Plan/issues/3041

**Closed by AuroraLS3** 2023-07-09 14:39 UTC
Labels: Bug
