### ISSUE TITLE
Using proxy on another machine results in HPE_UNEXPECTED_CONTENT_LENGTH

### ISSUE THREAD

**Issue by Starystars67** [plan-player-analytics/Plan#1488] opened 2020-06-10 00:05 UTC
Hey firstly I want to start by saying this is an impressive bit of kit you guys have made here.

So the issue i have found / might be better suited to a question is that I am trying to setup plan behind a proxy server running on a separate server. The two machines are connected via vlan. I can connect to plan using the remote machine IP over vlan and it is using HTTP (due to proxy setting in the ssl settings). I then obviously want to use HTTPS when connecting over the domain name (outside the proxy and vlan) however i keep getting this returned: `HPE_UNEXPECTED_CONTENT_LENGTH`
Now I setup a small web server to confirm that HTTP traffic is working with the proxy from the remote machine and it is so the issue is with plan from what I can conclude. 

Are you able to assist in trying to resolve this?

**Comment by Rsl1122** [comment] 2020-06-10 06:07
> According to https://github.com/nodejs/node/blob/8b4af64f50c5e41ce0155716f294c24ccdecad03/deps/http_parser/http_parser.c
>
>The cause may be:
>
>   - Double content-length header
>   - Both headers present: chunked encoding & content length
>
> ~ https://github.com/sindresorhus/got/issues/646#issuecomment-433610441

Plan uses `Content-Length` header, if your proxy adds a `Transfer-encoding: chunked` or another `Content-Length` header then that might be causing this issue.

**Comment by Rsl1122** [comment] 2020-06-11 06:24
From their error stacktrace it says `addChunk` so I'm guessing the proxy is using `Transfer-encoding: chunked` You might want to try filtering the `Content-Length` header from Plan responses in your proxy configuration to see if it fixes it.

**Comment by Starystars67** [comment] 2020-06-12 18:08
Im working on that now. Will report back with a result either way.

**Comment by Rsl1122** [comment] 2020-08-08 08:29
Closing as solved

**Comment by skerit** [comment] 2020-11-25 10:55
I'm also getting this issue since a few versions. I run plenty of other sites behind the proxy that also set `content-length` though, so I'm not sure where the issue is currently.

**Comment by Rsl1122** [comment] 2020-11-25 11:04
Hi @skerit 
Build 791 had one commit that changed how content-length was set for http 204 responses. https://github.com/plan-player-analytics/Plan/commit/0ac5ad6f23391ab5a023b577cf037e13f0f1a6d0

You can test if those responses are the cause by testing with build 770 https://github.com/plan-player-analytics/Plan/releases/tag/5.1.770

If they are caused by that, see what your proxy sends back for a `HEAD` response, as those might be the ones causing issues in your case (Assuming it is a new thing from recent changes)

**Comment by skerit** [comment] 2020-11-25 11:13
Alright I'll see if I can try that later.

In the mean time, I did make a request to the Plan webserver directly (not going through the proxy) and it most definitely is sending both a `content-length` and `transfer-encoding: chunked` header:

```
curl -i http://localhost:8804/server/Blackblock
HTTP/1.1 200 OK
X-robots-tag: noindex, nofollow
Date: Wed, 25 Nov 2020 11:08:04 GMT
Access-control-allow-methods: GET, OPTIONS
Transfer-encoding: chunked
Content-type: text/html; charset=utf-8
Access-control-allow-origin: *
Access-control-allow-credentials: true
Content-length: 101778
Accept-ranges: bytes
```

**Comment by Rsl1122** [comment] 2020-11-25 11:42
I don't unfortunately know what is setting that header on the response as there are no calls in the Plan code to set the transfer-encoding header, nor any implementation for a chunked transfer - but I can see that header on my test setup as well.

I tried to print what headers Plan has set:
![image](https://user-images.githubusercontent.com/24460436/100222971-8c59fa80-2f23-11eb-80e3-b0ff02fc0d71.png)
as seen here, they are not set, but when the response reaches Firefox it has that header
![image](https://user-images.githubusercontent.com/24460436/100223081-aeec1380-2f23-11eb-8557-e79d79420b3e.png)

So I think that the header is either set by the library I am using as the webserver, or it is inferred by HTTP clients from other properties of the response (I'm unaware what those might be).
Either way it is a bit problematic as I can't probe further into the library or firefox to find out which one it is.

**Comment by skerit** [comment] 2020-11-25 11:45
Hmm, could you maybe manually set it to `transfer-encoding: identity`? That seems like a very "vanilla" setting, maybe the library would then ignore it?

**Comment by Rsl1122** [comment] 2020-11-25 11:53
I can try that. Seems like bit more work than just setting it because that requires the content length header and gzip encoded stuff would probably require gzip instead

**Comment by AuroraLS3** [comment] 2021-02-12 11:40
Ok I found where the chunked transfer encoding is being set https://docs.oracle.com/javase/7/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpExchange.html#sendResponseHeaders(int,%20long)

**Closed** 2021-02-12 11:52 UTC
Labels: Question
