### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by LucidAPs** [plan-player-analytics/Plan#3108] opened 2023-07-09 08:11 UTC
[10:45:44 ERROR]: [Plan] Ran into ClassCastException - logged to plugins/Plan/logs/ClassCastException-e81dae982a.txt
[10:45:44 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:45:44 ERROR]: [Plan] Error msg: "class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @619a5dff)"

On bungee network, these are errors on the backend servers
Plan-5.5-build-2391

I assume its related to this
https://github.com/PaperMC/Paper/issues/9455

**Comment by AuroraLS3** [comment] 2023-07-09 09:26
Duplicate of #3098

**Closed by AuroraLS3** 2023-07-09 09:26 UTC
Labels: Bug
