### ISSUE TITLE
Error while starting the server with registering essentials extension

### ISSUE THREAD

**Issue by BillZhucn** [plan-player-analytics/Plan#1344] opened 2020-02-26 03:18 UTC
### Server information

Plan info: 
[11:15:56 INFO]:   版本：5.0 build 415
[11:15:56 INFO]:   更新可用：否
[11:15:56 INFO]:   可用数据库：SQLite (OPEN)
[11:15:56 INFO]:   已连接至Bungee：否
server info:
[11:16:38 INFO]: This server is running Paper version git-Paper-118 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[11:16:38 INFO]: Checking version, please wait...
[11:16:40 INFO]: You are 2 version(s) behind
Essentials info:
[11:17:09 INFO]: Server 版本n: 1.15.2-R0.1-SNAPSHOT git-Paper-118 (MC: 1.15.2)
[11:17:09 INFO]: EssentialsX 版本n: 2.17.2.1
[11:17:09 INFO]: LuckPerms 版本n: 5.0.72
[11:17:09 INFO]: PlaceholderAPI 版本n: 2.10.4
[11:17:09 INFO]: Vault 版本n: 1.7.2-b107
[11:17:09 INFO]: EssentialsXProtect 版本n: 2.17.2.1
[11:17:09 INFO]: EssentialsXChat 版本n: 2.17.2.1
[11:17:09 INFO]: EssentialsXGeoIP 版本n: 2.17.2.1
[11:17:09 INFO]: EssentialsXSpawn 版本n: 2.17.2.1

### Exceptions & Other Logs

```
[11:12:59 INFO]: [Plan] Registered extension: Essentials
[11:12:59 WARN]: [Plan] Encountered unexpected error with Essentials Extension: java.lang.IllegalArgumentException: class com.djrapitops.extension.EssentialsExtension method totalServerBalance could not be called: null (failed safely) when updating value for server, stack trace to follow (please report this):
[11:12:59 WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer
java.lang.IllegalArgumentException: class com.djrapitops.extension.EssentialsExtension method totalServerBalance could not be called: null
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:51) ~[?:?]        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:193) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:183) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:160) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.updateServerValues(ExtensionServiceImplementation.java:198) ~[?:?]
        at com.djrapitops.plan.extension.ExtensionServiceImplementation.lambda$register$0(ExtensionServiceImplementation.java:109) ~[?:?]
        at com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78) ~[?:?]                      at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]        ... 10 more
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.LinkageError: loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "net/ess3/api/events/MuteStatusChangeEvent"        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215) ~[patched_1.15.2.jar:git-Paper-118]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.15.2.jar:git-Paper-118]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.15.2.jar:git-Paper-118]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.15.2.jar:git-Paper-118]
        at com.earth2me.essentials.UserMap.getUser(UserMap.java:111) ~[?:?]
        at com.djrapitops.extension.EssentialsExtension.totalServerBalance(EssentialsExtension.java:154) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]        ... 10 more
Caused by: java.lang.LinkageError: loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "net/ess3/api/events/MuteStatusChangeEvent"
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_101]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_101]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.15.2.jar:git-Paper-118]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:201) ~[patched_1.15.2.jar:git-Paper-118]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.15.2.jar:git-Paper-118]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-118]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
        at com.earth2me.essentials.UserMap.load(UserMap.java:159) ~[?:?]
        at com.earth2me.essentials.UserMap.load(UserMap.java:23) ~[?:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.15.2.jar:git-Paper-118]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.15.2.jar:git-Paper-118]        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.15.2.jar:git-Paper-118]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.15.2.jar:git-Paper-118]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.15.2.jar:git-Paper-118]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.15.2.jar:git-Paper-118]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.15.2.jar:git-Paper-118]
        at com.earth2me.essentials.UserMap.getUser(UserMap.java:111) ~[?:?]
        at com.djrapitops.extension.EssentialsExtension.totalServerBalance(EssentialsExtension.java:154) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:63) ~[?:?]
        at com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:46) ~[?:?]        ... 10 more
```

**Comment by Rsl1122** [comment] 2020-02-26 09:41
Probably caused by commit 4e8f509ebcd54ae52746ca0c7cf075559a18cc29

Because the commit did not solve the proper issue this problem can most likely be fixed by reverting the offending commit.

**Closed** 2020-02-29 08:00 UTC
Labels: Bug, p: 1
