### ISSUE TITLE
ServerInfoFile resetting if server is shutdown during patches

### ISSUE THREAD

**Issue by XeroZon** [plan-player-analytics/Plan#2768] opened 2022-12-04 17:54 UTC
### Describe the issue
Recently I've noticed many new server instances being registered across my Bungee Network setup of Plan, I did some testing and figured out that the issue occurs when the server is restarted during the Patches. The file "ServerInfoFile.yml" will be set removed and recreated during that process.
``` (The Patches)
> [17:50:53 INFO]: [Plan] Applying Patch: BadNukkitRegisterValuePatch..
> [17:50:55 INFO]: [Plan] Applying Patch: PlayerTableRowPatch..
```
![image](https://user-images.githubusercontent.com/32605820/205507068-5d3e7286-27eb-485f-be1a-9884f22b1f0a.png)

### Exceptions & Other Logs

```
[DataExtensionMethodCallException-6fff2d8ce9.txt](https://github.com/plan-player-analytics/Plan/files/10149132/DataExtensionMethodCallException-6fff2d8ce9.txt)
```

### Plugin versions
I was using "Plan-5.4-build-1583.jar" and have since upgraded to the last Java 8 version "Plan-5.4-build-1722.jar"

### Additional information
N/A

**Comment by AuroraLS3** [comment] 2022-12-04 18:50
Thanks for letting me know, this issue has been difficult to reproduce and I wasn't able to do that last time it was reported.

**Comment by AuroraLS3** [comment] 2022-12-05 14:55
Closing as duplicate of #2254

**Closed by AuroraLS3** 2022-12-05 14:55 UTC
Labels: Bug
