### ISSUE TITLE
login system without https

### ISSUE THREAD

**Issue by msn-95** [plan-player-analytics/Plan#2916] opened 2023-03-12 00:41 UTC
### I would like to be able to..

i would like to enable login without https as i am using ptero

### Is your feature request related to a problem? Please describe.

rn idk how to enable https because i dont have root access

**Comment by AuroraLS3** [comment] 2023-03-12 07:43
You can create the certificate on your own PC and upload it to pterodactyl

**Comment by AuroraLS3** [comment] 2023-03-12 07:45
Closing as duplicate of #2303

**Closed by AuroraLS3** 2023-03-12 07:45 UTC
