### ISSUE TITLE
Database failed to open

### ISSUE THREAD

**Issue by mercadanteus** [plan-player-analytics/Plan#2387] opened 2022-06-02 15:32 UTC
### Describe the issue
Database failed to open, Query has failed

### Exceptions & Other Logs
CONSOLE MSG:  https://www.toptal.com/developers/hastebin/ovinedixek.yaml
EXCEPTION:    https://www.toptal.com/developers/hastebin/aburujijig.nginx
```

```

### Plugin versions
Player Analytics 5.4 build 1690

### Additional information
Working ok in previous version, had to revert to it

**Comment by AuroraLS3** [comment] 2022-06-02 16:14
Please provide full enable log from Plan logo to end of whatever errors came after, as well as related error files.

The linked error information is insufficient to figure out the cause

**Comment by AuroraLS3** [comment] 2022-06-09 19:08
Closing this due to no reply - Provide more information and I'll reopen

**Closed by AuroraLS3** 2022-06-09 19:08 UTC
Labels: Bug, status: Awaiting Reply
