### ISSUE TITLE
DataExtension ViaVersion, errors after 1628 Update

### ISSUE THREAD

**Issue by Pingger** [plan-player-analytics/Plan#2334] opened 2022-04-16 10:58 UTC
### Describe the issue
ViaVersion DataExtension is not updated for the 1628 Database layout.

### Exceptions & Other Logs

```
ff703f2a30 - Last occurred: 2022-04-16 Occurrences: 1
---- Context 1 ----
Plan v5.4 build 1628
BungeeCord git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
Server vgit:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483

Report and/or disable ViaVersion extension in the Plan config.
ViaVersion
Method:protocolTable
Error code: 1054
SELECT protocol_version, COUNT(1) as count FROM plan_version_protocol INNER JOIN plan_user_info on plan_version_protocol.uuid=plan_user_info.uuid WHERE plan_user_info.server_uuid=? GROUP BY protocol_version
SQL Grammar error

---- Stacktrace ----
com.djrapitops.plan.exceptions.DataExtensionMethodCallException: ViaVersion.protocolTable errored: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Unknown column 'plan_user_info.server_uuid' in 'where clause'
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:56)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildTable$0(DataValueGatherer.java:159)
   com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:391)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeTable(DataValueGatherer.java:446)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$28(DataValueGatherer.java:354)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:354)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:313)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:183)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:176)
   com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
java.lang.reflect.InvocationTargetException
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:568)
   com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:64)
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildTable$0(DataValueGatherer.java:159)
   com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:391)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeTable(DataValueGatherer.java:446)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$28(DataValueGatherer.java:354)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:354)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:313)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:183)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:176)
   com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Unknown column 'plan_user_info.server_uuid' in 'where clause'
   com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:144)
   com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeWithConnection(QueryAPIQuery.java:58)
   com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeQuery(QueryAPIQuery.java:46)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:307)
   com.djrapitops.plan.query.QuerySvc.query(QuerySvc.java:81)
   com.djrapitops.extension.ViaVersionStorage.getProtocolVersionCounts(ViaVersionStorage.java:122)
   com.djrapitops.extension.ViaVersionExtension.protocolTable(ViaVersionExtension.java:84)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:568)
   com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:64)
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildTable$0(DataValueGatherer.java:159)
   com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:391)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeTable(DataValueGatherer.java:446)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$28(DataValueGatherer.java:354)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:354)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:313)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:183)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:176)
   com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)
Caused by:
java.sql.SQLSyntaxErrorException: Unknown column 'plan_user_info.server_uuid' in 'where clause'
   com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
   com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
   com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
   com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
   plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
   plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
   com.djrapitops.extension.ViaVersionStorage.lambda$getProtocolVersionCounts$4(ViaVersionStorage.java:124)
   com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeWithConnection(QueryAPIQuery.java:56)
   com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeQuery(QueryAPIQuery.java:46)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:307)
   com.djrapitops.plan.query.QuerySvc.query(QuerySvc.java:81)
   com.djrapitops.extension.ViaVersionStorage.getProtocolVersionCounts(ViaVersionStorage.java:122)
   com.djrapitops.extension.ViaVersionExtension.protocolTable(ViaVersionExtension.java:84)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:568)
   com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:64)
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildTable$0(DataValueGatherer.java:159)
   com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:391)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeTable(DataValueGatherer.java:446)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$28(DataValueGatherer.java:354)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:354)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:313)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:183)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:176)
   com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   java.base/java.lang.Thread.run(Thread.java:833)

```

### Plugin versions
Plan 1628

### Additional information
Would have made the issue over at https://github.com/plan-player-analytics/Extension-ViaVersion, but issues are disabled there

**Comment by AuroraLS3** [comment] 2022-04-16 10:59
Duplicate of #2330

**Comment by Pingger** [comment] 2022-04-16 10:59
yupp I'm blind sorry

**Closed by AuroraLS3** 2022-04-16 10:59 UTC
Labels: Bug
